### ISSUE TITLE
Fix Warpaint and Skin unintentional wrappin

### ISSUE THREAD

**Issue by Wosheereal** [mastercomfig/team-comtress-2#105]
A bug where the back scratcher, bazaar bargain, black box, disp action, flame thrower, loose cannon, medigun, minigun, rocket launcher, smg, sniper rifle, and tomislav  would get unintentional texture wrap issues (as shown in screenshots).

To recreate this bug, you have to aquire a weapon skin.

A easy way to fix the issue would be to add a visible line or remove random number generation of skins so that it would be the same every time.

**Screenshots**
https://imgur.com/a/0hPAFNP

**Comment by Yttrium-tYcLief** [comment]
This is an art issue (and a design flaw), which can't really be addressed with this project.
