### ISSUE TITLE
Your enternal reward: cloak not being taken away

### ISSUE THREAD

**Issue by avinzombie** [mastercomfig/team-comtress-2#107]
You can redisguise any were and no loss in cloak meter

**Comment by paypur** [comment]
are you sure you arent testing this in spawn?

**Comment by avinzombie** [comment]
No its not spawn I can disguise any were with the weapon and not get my cloak effected in any way

**Comment by wgetJane** [comment]
comtress is based on pre-Jungle Inferno tf2

**Comment by Yttrium-tYcLief** [comment]
Closing since it's an unsolvable project issue and not an actual TF2 one.
