### ISSUE TITLE
64-bit compatibility

### ISSUE THREAD

**Issue by melvyn2** [mastercomfig/team-comtress-2#113]
**Is your feature request related to a problem? Please describe.**
Slightly; Memory usage runs dangerously close to the 32-bit limit, especially on macOS due to texture memory allocation issues.

**Describe the solution you'd like**
Overhaul 32-bit specific code so that it does not rely on a specific memory size, and add 64-bit code with #ifdefs in areas that are not possible to generalize.

**Describe alternatives you've considered**
Fix the memory fragmentation issues on the platforms on which this is an issue.

**Additional context**
Very High texture quality is disabled on macOS for this reason.
[ValveSoftware/Source-1-Games#2238](https://github.com/ValveSoftware/Source-1-Games/issues/2238) contains a lot of pertinent information.
Additionally, both CS:GO and Garry's Mod have been ported to 64-bits.

**Comment by micwoj92** [comment]
@melvyn2 with Apple moving to arm, amd64 based macos machines will be obsolete.

**Comment by melvyn2** [comment]
Intel macs will still be supported for at least 5 years, probably 7, so they will still not be obsolete for a while.

**Comment by micwoj92** [comment]
Valve time.

**Comment by melvyn2** [comment]
I just realized #67 exists; I'll move the extra info there and close this issue.
