### ISSUE TITLE
Quick FrameView Performace Comparison

### ISSUE THREAD

**Issue by Kenajcrap** [mastercomfig/team-comtress-2#114]
[NVIDIA's FrameView](https://www.nvidia.com/en-us/geforce/technologies/frameview/) is a quick way to get very granular game performance data. This wasn't a super controlled test but I was so impressed with your build when I first tried it out that I wanted to look at some numbers, so here we go:

### Setup:
- ASUS PRIME B450M-GAMING/BR
- AMD Ryzen 5 3600 6-Core Processor, 3593 Mhz, 6 Core(s), 12 Logical Processor(s)
- EVGA GTX 1660 Super SC ULTRA GAMING (06G-P4-1068)
- 2x8GB TEAMGROUP-UD4-3000 3000MHz DDR4 (16-16-16-39)

### Methodology:
- No other programs running besides hl2.exe and Steam
- No custom hubs
- No custom configs (mastercomfig or similar)
- All max settings except for blur (turned off), vertical sync (turned off) and AA (turned off)
- Find match > Create server > pl_upward
- tf_bot_add 24
- Spectate the cart facing forward
- Start capturing at the end of the setup time
- Stop capturing data after 1 minute
- The matches chosen for comparison had similar choke points and number of gibs exploded around

### Raw data:
FrameView outputs to .csv files, just rename the attached .txt to .csv and you are golden
[FrameView_hl2.exe TC2.txt](https://github.com/mastercomfig/team-comtress-2/files/5222354/FrameView_hl2.exe.TC2.txt)
[FrameView_hl2.exe_TF2.txt](https://github.com/mastercomfig/team-comtress-2/files/5222355/FrameView_hl2.exe_TF2.txt)

### Results:
FrameView includes a Template Spreadsheet where you can paste captures to get some data out, here is some info taken from that.

Averages
![image](https://user-images.githubusercontent.com/25385928/93163741-3af4ea00-f6ee-11ea-8e1c-f2c141f2acf0.png)![image](https://user-images.githubusercontent.com/25385928/93163953-cc645c00-f6ee-11ea-97da-a3489ddb889c.png)

1st Percentiles
![image](https://user-images.githubusercontent.com/25385928/93163817-74c5f080-f6ee-11ea-9970-39a1c782fd82.png)![image](https://user-images.githubusercontent.com/25385928/93163987-dd14d200-f6ee-11ea-90a6-9162a6bab231.png)

90th Percentiles
![image](https://user-images.githubusercontent.com/25385928/93163838-814a4900-f6ee-11ea-9a4f-02705d1d8626.png)![image](https://user-images.githubusercontent.com/25385928/93164003-e605a380-f6ee-11ea-834d-50ed69d6a6c2.png)

99th Percentiles
![image](https://user-images.githubusercontent.com/25385928/93163862-945d1900-f6ee-11ea-8c29-3860b81f683e.png)![image](https://user-images.githubusercontent.com/25385928/93164011-ed2cb180-f6ee-11ea-90f9-3720d42d20fe.png)

Maximum
![image](https://user-images.githubusercontent.com/25385928/93164042-fa49a080-f6ee-11ea-928e-f9e54f501b6e.png)![image](https://user-images.githubusercontent.com/25385928/93164064-046b9f00-f6ef-11ea-89b5-b35d4ece9f91.png)

Frametime - full capture
![image](https://user-images.githubusercontent.com/25385928/93164457-e6526e80-f6ef-11ea-909f-0f3ea78de310.png)

Frametime - seconds 5 to 15 (team wipe at the cart on both data captures, loads of gibs and particles)
![image](https://user-images.githubusercontent.com/25385928/93164612-506b1380-f6f0-11ea-825a-191c9e7b474e.png)

Render Queue Depth
![image](https://user-images.githubusercontent.com/25385928/93164645-6c6eb500-f6f0-11ea-9517-83e4f4bd470f.png)

### Next Steps
- Other Maps
- Maybe capturing data during the next server playtest
- Is there a way to spawn bots wearing cosmetics? I would love to test the impact of that!

I find these results to be downright insulting to valve in how impressive they are. It feels like I'm playing a SFM short in how smooth the game plays, the particles look smoother and less prone to glitching too, but that may be just placebo. Thank you for this awesome project and I hope this information was useful.

**Comment by Yttrium-tYcLief** [comment]
Bots can be created with non-stock weapons using [this SourceMod plugin](https://forums.alliedmods.net/showthread.php?t=287668), and can be given cosmetics [with this one](https://forums.alliedmods.net/showthread.php?t=287668).

Not using SourceMod, one possible option might be equipping cosmetics on MvM robots using custom mission files: https://mvm.tf/

**Comment by Yttrium-tYcLief** [comment]
Agree with the close. further discussion should take place on discord
