### ISSUE TITLE
64 bit support so TF2 can run on MacOS post Catalina

### ISSUE THREAD

**Issue by Gamepro5** [mastercomfig/team-comtress-2#115]
Many people, including myself, were disappointed when they accidentally updated their Macs and found out Apple removed 32 bit support for some reason. This made us unable to launch TF2.

I never understood how CSGO is still able to run on macs post catalina. You've made some improvements to TF2 from CSGO, so I was wondering if it would be possible to also build the project in 64 bit so we can hopefully run TF2 again on MacOS.

People often say to try and downgrade to Mojave but that seems like a bad and temporary solution. Eventually we will have to upgrade our OS because of security patches. I also tried dual booting Ubuntu linux, but that simply does not work as well as MacOS for some Macs.

[Additional context](https://support.steampowered.com/kb_article.php?ref=1055-ISJM-8568)

**Disclaimer:** Sorry if this was a stupid request and it is not possible, there is a reason I don't deal with stuff this low level. I am not sure if it's even possible, after all, Valve would have done it by now if it was.

**Comment by melvyn2** [comment]
#113 ?

**Comment by mastercoms** [comment]
Yes

**Comment by micwoj92** [comment]
@Gamepro5 gamenoob5

**Comment by Gamepro5** [comment]
Sorry, I didn't realize someone posted the same request while I was making this one.
