### ISSUE TITLE
And linux.

### ISSUE THREAD

**Issue by Ohio2** [mastercomfig/team-comtress-2#116]
**Is your feature request related to a problem? Please describe.**
I can't even boot the game up without wine on linux.

**Describe the solution you'd like**
Just update it to support linux.

**Additional context**
I know for one thing, WINE and Proton can fail.

**Comment by Juesto** [comment]
Literally this is being worked on, no need to stack issues.

**Comment by melvyn2** [comment]
#2

**Comment by Ohio2** [comment]
Okay, if it's worked on, then i closed the issue.
