### ISSUE TITLE
Rename launcher executable

### ISSUE THREAD

**Issue by melvyn2** [mastercomfig/team-comtress-2#117]
Based off of [this comment](https://github.com/mastercomfig/team-comtress-2/issues/30#issuecomment-682221117).
**Is your feature request related to a problem? Please describe.**
The current launcher executable is named hl2.exe, hl2_osx, hl2_linux, etc. I think the launcher should reflect that this game is not half-life 2. Additionally, this would supposedly fix needing the `-game tf` argument.

**Describe the solution you'd like**
Change the name of the `launcher_main` output executable to tf2.exe, tf2_osx, tf2_linux, and fix any references to it.

**Additional context**
This will probably break launching TC2 from steam, as it probably looks for the hl2 executable - a symlink might fix this.

**Comment by mastercoms** [comment]
This can break a lot of things, including per application settings as well as graphics drivers that do optimizations based on the game.
