### ISSUE TITLE
[Bug Fix Request] Gunslinger Combo Critical Hit Registration Hitbox/Lag Problems

### ISSUE THREAD

**Issue by DemoPhone** [mastercomfig/team-comtress-2#118]
**Describe the bug**
For the Gunslinger:
If an enemy is moving, the registration model(?) of the third punch critical hit appears to be in front of the player model. Even if you hit an enemy 3 times in a row but you are not aiming toward the direction that the player is moving, the third punch critical hit will not work. The twitchy hand animation that plays after the third punch critical hit hits an enemy and the kill feed icon with 3 strikes also does not play or show properly if you hit an enemy with the third punch and you hit them anywhere other than the direction that they are moving. The same issue exists with the registration model of the speed boost for the disciplinary action, but that appears to have been fixed already on here. 

**How you encountered the issue**
I have encountered these problems numerous times during typical casual and community server game-play where the mechanics fail to work as they should because of what looks like improperly synchronized hitboxes or lag compensation. This issue has existed for many years, so it should be in this build of TF2 as well (unless it has already been fixed and I missed it). 

**Screenshots**
I have a short video that showcases the issues (it is difficult to show these by just screenshots). This is not just a problem on tr_walkway; it occurs quite often in all modes, maps, etc. of TF2. Apologies for the low quality (this was recorded a long time ago, but they still showcase the issue nonetheless). 
Gunslinger Problem:
https://www.youtube.com/watch?v=jM0C-Hyq2Es

**Comment by wgetJane** [comment]
> For the Disciplinary Action:
> If a teammate is moving, the registration model of the speed boost is in front of the player model. Even if you hit a teammate but you are not aiming toward the direction that the player is moving, the speed boost will not work. 

already fixed: https://github.com/mastercomfig/team-comtress-2/commit/f55e678d392da408bbb60dc693601ea1f643b7af

**Comment by micwoj92** [comment]
@DemoPhone please report 1 issue per ticket.

**Comment by Yttrium-tYcLief** [comment]
Can we have some testing and confirmation on whether f55e678 actually fixed this particular issue, since this issue mentions the Gunslinger as well?

**Comment by micwoj92** [comment]
@Yttrium-tYcLief this should be split in 2 tickets. One is resolved one is not as far as I know *the gunslinger one being unsolved.

**Comment by Yttrium-tYcLief** [comment]
Since it was the first one mentioned, let's treat this issue for the Gunslinger, and ignore the Disciplinary Action portion of it.

**Comment by micwoj92** [comment]
Thank you (y)

**Comment by DemoPhone** [comment]
Apologies for my unawareness of the Disciplinary Action fix. This post now focuses solely on the Gunslinger problem, but alludes to the fact that it may stem from a similar issue that the disciplinary action had.

**Comment by wgetJane** [comment]
the game doesn't perform lag compensation when checking for consecutive hits:
https://github.com/mastercomfig/team-comtress-2/blob/d7acbf3917abce0e5976dc1b906b50c5e80176fc/game/shared/tf/tf_weapon_wrench.cpp#L484-L513
