### ISSUE TITLE
Issue templates do not assign tags automatically

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/team-comtress-2#125]
**Describe the bug**
THis is a bug report, it should get a bug label and it does not

**How you encountered the issue**
1. make bug report.
2. it has no bug label

**Screenshots**
N/A

(I just copied these from mastercomfig repo and there it works, no idea why it doesn't here)

**Comment by Yttrium-tYcLief** [comment]
This repo hasn't been fully configured with auto labels, it'll be done soon

**Comment by maximsmol** [comment]
#194

**Comment by Yttrium-tYcLief** [comment]
why add tc2-issue? this is a meta thing, tc2 should be reserved for actual client problems

**Comment by maximsmol** [comment]
This is done
