### ISSUE TITLE
Add more tags

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/team-comtress-2#130]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I think about @Yttrium-tYcLief 's hard life when he does not have enough tags to label issues.

**Describe the solution you'd like**
Add label labels:
- split "bug" into "Valve Bug" and "TC2 Bug"
- add "Anticheat"
- add "typo"

**Describe alternatives you've considered**
Give @Yttrium-tYcLief permissions to edit labels 

**Additional context**
none

**Comment by Yttrium-tYcLief** [comment]
>Give @Yttrium-tYcLief permissions to edit labels

I think this requires giving me much higher access to the repo. I'm fine without that. Once the new labels are in place, I'll be happy.

**Comment by micwoj92** [comment]
> > Give @Yttrium-tYcLief permissions to edit labels
> 
> I think this requires giving me much higher access to the repo. I'm fine without that. Once the new labels are in place, I'll be happy.

Do you know if the permissions can be refined or are just like general levels that you can't edit?

**Comment by Yttrium-tYcLief** [comment]
Not a clue. I'm familiar enough with Github's tracking system to use it, but that's about it.

**Comment by micwoj92** [comment]
Ok, this can be closed now
