### ISSUE TITLE
Better issue tags

### ISSUE THREAD

**Issue by henke37** [mastercomfig/team-comtress-2#136]
The "won't fix" tag seems to be used for several purposes. It would help clarify if there were tags such as "can't fix" and "out of scope".

**Comment by Yttrium-tYcLief** [comment]
I've been mostly using the "invalid" tag for "out of scope" but I agree that having a tag strictly for out of scope would be nice.

"Can't fix" is likely already included in "out of scope".

**Comment by maximsmol** [comment]
We have no "can't fix" things so far. Closing this because a "can't fix" label is not a common thing to have and because there is no demonstrated need for this.
