### ISSUE TITLE
Fixing the Dragon's Fury (as well as other weapons' projectiles)

### ISSUE THREAD

**Issue by jpmrocks** [mastercomfig/team-comtress-2#142]
While Pyro's flames are bugged as a whole (maxing at 80DPS), the Dragon's Fury in particular is extra buggy.
List of bugs from the wiki:
- The Dragon's Fury can potentially lag or freeze the player using it for a second while firing.
* This is because the max particle count of the Fireball is set to 1000.
* Changing r_dynamic, r_dynamiclighting, and r_maxdlights to 0 will fix this issue. Because there are no other dynamic lights, there are no significant visual changes.
- The projectile can go through thin walls such as setup gates when fired at a correct angle.
- The attribute Deals 300% damage to burning players is incorrect; the bonus damage also applies to buildings and other non-player targets. In reality it is likely that the bonus damage is really the base damage of the weapon, and that hits against non burning players is reduced.
- Dragon Slayer skins of the weapon will not be sorted by Quality, as it is an Elite Grade weapon and is sorted by Decorated quality.
- The Festivized variant's icon is team-colored (red icon on RED, blue icon on BLU) instead of being a single color.
- The attribute No random critical hits is missing.
- The fireball projectile can become harmless by colliding with certain projectiles. Specifically rockets, needles, Huntsman arrows, Rescue Ranger bolts, flares, and the Fireball spell.
- When killed/killing via reflecting the weapon's projectile, this weapons shows a reflected rocket kill-icon in the killfeed.
- The projectile can collide with certain invisible map elements that it is supposed to pass through, effectively making the projectile disappear mid-air in some map locations. Examples include the lowest level of the wooden platforms near the rocks on both of the second control points on Gullywash, and the room with a raised pathway near the final red spawn on Frontier.

Other issues (tho I'm not sure if theyre bugs or not) include enemy hitbox detection sometimes just not detecting a secondary hit, due to the projectile server side needing to land squarely in the center of the enemy's hitbox. Meaning, increased damage will not apply in most situations, even if the player lands a secondary hit.

https://www.youtube.com/watch?v=5QPxiTh9J98 Video showing projectile collision issues.
https://www.youtube.com/watch?v=TaxJLWyTiFI Video showing other collision issues.

**Comment by micwoj92** [comment]
@jpmrocks you should create 1 ticket per issue for better tracking.

**Comment by Yttrium-tYcLief** [comment]
I haven't tested or looked into it but it is very likely that the Dragon's Fury (as well as the flamethrower rework) doesn't even exist in this codebase, since the leak predates some later JI development. If that's the case, it wouldn't be possible to address this issue in this project.

**Comment by micwoj92** [comment]
@Yttrium-tYcLief Dragon Furry kinda exist, but is nowhere near being the same as the one from live tf.

**Comment by mastercoms** [comment]
> The projectile can collide with certain invisible map elements that it is supposed to pass through, effectively making the projectile disappear mid-air in some map locations. Examples include the lowest level of the wooden platforms near the rocks on both of the second control points on Gullywash, and the room with a raised pathway near the final red spawn on Frontier.

This was already fixed

**Comment by Yttrium-tYcLief** [comment]
Because this issue is about a weapon that we basically have no control over, I'm going to close this issue, *however*:

> Changing r_dynamic, r_dynamiclighting, and r_maxdlights to 0 will fix this issue. Because there are no other dynamic lights, there are no significant visual changes.

We should be able to fix this issue with particle and lighting optimizations, although we can't actually test how much that helps in this specific case.
