### ISSUE TITLE
Atomizer | third jump deals -10 hp

### ISSUE THREAD

**Issue by FinecoFinit** [mastercomfig/team-comtress-2#148]
**How you encountered the issue**
1. start server
2. pick scout
3. jump 3 times

**Desktop (please complete the following information):**
* Team Comtress version (don't say latest, say the actual version): 0.0.16
* Custom content (if any): mastercomfig, custom animations
* DX level: 9
* Launch options: hl2.bat -novid -nojoy -nosteamcontroller -nohltv -particle_fallback 2 %* < nul
* Operating system (OS): Windows 10 2004
* Graphics card (GPU): AMD Radeon RX 560
* Graphics driver version: 20.5.1
* Processor (CPU): Q9500
* TC2 on HDD or SSD: HDD
* Memory (RAM) size in MB or GB: 6 GB

**Comment by micwoj92** [comment]
This is pre jungle inferno, invalid.

**Comment by treacherousfiend** [comment]
this is not an issue, comtress is based off of a pre Jungle Inferno version of TF2, and that is how the atomizer used to work

**Comment by FinecoFinit** [comment]
Ok, but why item stats show actual balance?

**Comment by treacherousfiend** [comment]
since comtress is installed over the current version of tf2, it uses the item schema (backpack text, loadout text) from that version. the actual weapon code however, is pre JI. aside from stuff that has been ported over (see panic attack)
