### ISSUE TITLE
host_timescale incorrectly set to 0 instead of 1

### ISSUE THREAD

**Issue by some-username-here1** [mastercomfig/team-comtress-2#164]
**Describe the bug**
Said in the title.

**How you encountered the issue**
When I was messing around in a offline server, I saw in the developer console that `host_timescale` was incorrectly set to `0` instead of `1` (unlike regular tf2).

**Comment by mastercoms** [comment]
This is intentional. host_timescale 0 skips scaling of the time.

**Comment by Yttrium-tYcLief** [comment]
Is there any *upside* to making it default to 0 instead of 1? Just out of curiosity.

**Comment by mastercoms** [comment]
Yes, because it allows for branch optimization to skip host_timescale branches.

**Comment by Yttrium-tYcLief** [comment]
Gotcha, makes sense

**Comment by some-username-here1** [comment]
oh alright, my bad
