### ISSUE TITLE
[Request] Allow sound to continue playing when applying changed sound option

### ISSUE THREAD

**Issue by some-username-here1** [mastercomfig/team-comtress-2#175]
**Is your feature request related to a problem? Please describe.**
Whenever applying changes after checking (or un-checking) the "Silence the audio while the game window is in the background." option, whatever the sound engine was playing gets stopped immediately.

**Describe the solution you'd like**
The Linux version of TF2 (or maybe any Source game) was somehow able to get around this, so would it be possible to get this into the Windows version?

**Additional context**
Moved from #168 into it's own issue.

**Comment by mastercoms** [comment]
This is unavoidable. The sound system has to restart to set this parameter in DirectSound. However, you may find some solace in that sound stutters have been eliminated due to the completely threaded sound system.

**Comment by some-username-here1** [comment]
Oh alright, that's a bummer. Do I leave this open with the `wontfix` label then, or is it safe to close?

**Comment by Yttrium-tYcLief** [comment]
I'll take care of it for you.
