### ISSUE TITLE
Buggy water reflection persists after map change when looking at a water surface from an angle

### ISSUE THREAD

**Issue by some-username-here1** [mastercomfig/team-comtress-2#177]
**Describe the bug**
Whenever a player happens to look at the top surface of water, regardless of what it's for and assuming it's large enough, the reflection would end up staying the same from then and continuing to happen upon later maps.

**How you encountered the issue**
Go to a body of water that a player is able to see up close and not far way, then try to start looking at it from certain angles. The reflection you saw should now glitch and show up in a out-of-place way, with possibly the surface underneath included and looking wrong or incorrect.
It's hard to pin down getting this bug to appear, since it's random at times and hard to pin-point.

**Screenshots**
![image](https://user-images.githubusercontent.com/34193156/93304880-57af2180-f7c3-11ea-9855-c58a4442a73b.png)
(map is `trade_stardust`)

**Desktop (please complete the following information):**
* Team Comtress version (don't say latest, say the actual version): 0.0.16
* Custom content (if any): TF2 Bot Overhaul (from GameBanana)
* DX level: 10.0
* Launch options: `-game tf -sv_pure 0 -novid -nojoy -nosteamcontroller -nohltv -reuse -threads 8 -w 1920 -h 1080 -sw -noborder`
* Operating system (OS): Windows 10 (64-bit)
* Graphics card (GPU): Nvidia GeForce GTX 1650
* Graphics driver version: Version 431.90
* Processor (CPU): Intel Core i5-9300H
* TC2 on HDD or SSD: HDD
* Memory (RAM) size in MB or GB: 16 GB

Moved from #168 into its own issue.

**Comment by Yttrium-tYcLief** [comment]
Happens to me too, notably on `cp_sunshine` after previously having loaded `mvm_decoy`.

**Comment by some-username-here1** [comment]
Are you sure it's just a tc2 issue? I've seen it happen on tf2 too, and even that's not often.

**Comment by Yttrium-tYcLief** [comment]
I'll label it as a TF2 issue until we're sure it only happens in TC2 after further testing.

**Comment by mastercoms** [comment]
I know the change in TC2 which introduced this. I will add more aggressive clearing to resolve this bug.

**Comment by Yttrium-tYcLief** [comment]
I guess that's enough confirmation it's TC2-only, lol

**Comment by some-username-here1** [comment]
What about these?
![image](https://user-images.githubusercontent.com/34193156/93309252-e70b0380-f7c8-11ea-9aab-97680c57c955.png)
![image](https://user-images.githubusercontent.com/34193156/93309431-26d1eb00-f7c9-11ea-8fc8-f4cf831ceeb7.png)
![image](https://user-images.githubusercontent.com/34193156/93309410-1d488300-f7c9-11ea-8384-904447d96753.png)
![image](https://user-images.githubusercontent.com/34193156/93309604-54b72f80-f7c9-11ea-844c-56fc2cd649bc.png)
I know the issue I'm bringing up also happens in TF2 too, but it's still hard to get it to encounter again that it's difficult

**Comment by mastercoms** [comment]
Also, on an unrelated note, you're using unoptimal launch options! Just use the ones that comes with the start script for TC2.

**Comment by some-username-here1** [comment]
Oh yeah, I was using it like that since I made a shortcut to `hl2.exe` as you can't specify which GPU to use with a batch file

**Comment by micwoj92** [comment]
the bat file still points to .exe

**Comment by wgetJane** [comment]
> Oh yeah, I was using it like that since I made a shortcut to `hl2.exe` as you can't specify which GPU to use with a batch file

were you running the game without the -insecure launch option

**Comment by some-username-here1** [comment]
> the bat file still points to .exe

I meant that since I'm on my laptop right now, and I wanted to see how much better would tc2 run compared to tf2, I had to use a shortcut link since the "Run with graphics processor" option when right-clicking a shortcut or exe doesn't show up with a bat file

> were you running the game without the -insecure launch option

pretty much, yeah...

**Comment by micwoj92** [comment]
> > the bat file still points to .exe
> 
> I meant that since I'm on my laptop right now, and I wanted to see how much better would tc2 run compared to tf2, I had to use a shortcut link since the "Run with graphics processor" option when right-clicking a shortcut or exe doesn't show up with a bat file

I am by no way expert in this, but it should work if you set it in executable options and then just run the bat file lol. did you test that?

**Comment by some-username-here1** [comment]
> I am by no way expert in this, but it should work if you set it in executable options and then just run the bat file lol. did you test that?

Not really, as I would have to set that from within the Nvidia control panel instead

**Comment by maximsmol** [comment]
Can we close this since #193 was merged?

**Comment by some-username-here1** [comment]
Here's a screenshot I was able to get of it happening in regular tf2 also, but I'm not sure if you would have to be a set distance from the water surface or view it at an odd angle
![image](https://user-images.githubusercontent.com/34193156/103497162-46d3fb80-4e06-11eb-9cff-bec7a5f01efe.png)

**Comment by some-username-here1** [comment]
@mastercoms

**Comment by mastercoms** [comment]
I don't think it's worth to fix such extreme cases which are likely limitations made for the sake of performance.
