### ISSUE TITLE
Items in last 10 pages (50 to 60) become unsorted!

### ISSUE THREAD

**Issue by CoolJosh3k** [mastercomfig/team-comtress-2#179]
**Describe the bug**
After running TC2, returning to TF2 shows that all items in pages 50 to 60 have now lost their positions.

**How you encountered the issue**
Have items in pages 50 or above, then run TC2. Return to TF2 to find those affected items moved back to the first available slots in your backpack.

**Desktop (please complete the following information):**
* Team Comtress version (don't say latest, say the actual version): 0.0.16
* Custom content (if any): none
* DX level: default
* Launch options: none
* Operating system (OS): Windows 10 64bit
* Graphics card (GPU): GTX 1070ti
* Graphics driver version: 452.06
* Processor (CPU): Intel i7 8086K
* TC2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 16GB

**Comment by Yttrium-tYcLief** [comment]
Possibly related to an unfinished implementation in 7d534f2?

**Comment by CoolJosh3k** [comment]
The sourcecode had an older limit of 2000 slots, right? Then the fix makes it 2500.

It needs to match the current limit of 3000, else it will mess with our inventory (for the last 500 slots) everytime they load TC2. TF2 currently has 60 pages of 50 slots each as a maximum.

**Comment by maximsmol** [comment]
Can you find any proof that the current limit is 3000? Like maybe the official patch note?

**Comment by micwoj92** [comment]
> Can you find any proof that the current limit is 3000? Like maybe the official patch note?

This was done in bluemoon

**Comment by maximsmol** [comment]
Fixed in master by coms
