### ISSUE TITLE
[Request] Proper up-to-date Closed Captions for newer voicelines

### ISSUE THREAD

**Issue by some-username-here1** [mastercomfig/team-comtress-2#181]
**Is your feature request related to a problem? Please describe.**
The Closed Captions as a whole, at this point, is no longer being worked on or updated.

**Describe the solution you'd like**
Given how Valve has given up on updating it for this game, by chance would it be alright to integrate this gamebanana mod into TC2, given the proper permissions and usage?
https://gamebanana.com/guis/35712

**Additional context**
Not that I can think of.

**Comment by henriquecm** [comment]
Not just the newer, all the one that are missing and give error log console

**Comment by Yttrium-tYcLief** [comment]
I think this is sort of outside the scope of this project.

**Comment by maximsmol** [comment]
There are currently no plans to update any of the game resources, including close caption files.
