### ISSUE TITLE
Demos recorded on TC2 0.0.16 cannot be played back on stock TF2, but a demo recorded on 0.0.9 works

### ISSUE THREAD

**Issue by Kenajcrap** [mastercomfig/team-comtress-2#191]
**Describe the bug**
Demos made in TC2 0.0.16 cannot be played back on TF2. However, a demo recorded on 0.0.9~0.0.10 works.

**How you encountered the issue**
I recorded a demo on TC2 0.0.16 and tried playing it back on a stock download of TF2

**Additional Information**
I've tried recording demos on TC2 with different contents, and tried playing them back on stock TF2 and on the pre_jungleinferno_demos beta branch;
The demos used for testing were:
- dustbowl_no_bots.dem (just spectating with no bots playing)
- dustbowl_no_action.dem (server full of bots but no action, that is, no fire, no shooting and no gibs. the whole demo was recorded during the setup time)
- dustbowl_action.dem (a section of a normal bot versus bot)
- upward_no_bots.dem
- upward_no_action.dem
- upward_action

here are the demos: 
[demos.zip](https://github.com/mastercomfig/team-comtress-2/files/5235090/demos.zip)

All of the demos were met with the same behavior on stock TF2, the game attempts to load the demo, then quits to the main menu, showing errors in the console:
[console_stock.log](https://github.com/mastercomfig/team-comtress-2/files/5235134/console_stock.log)

Same goes for the beta branch, but the game instead crashes with this warning:
![image](https://user-images.githubusercontent.com/25385928/93394325-6ee52200-f84a-11ea-800f-398dc303efd3.png)
There are also different errors in the console:
[console_pre_jungleinferno_demos_branch.log](https://github.com/mastercomfig/team-comtress-2/files/5235060/console_pre_jungleinferno_demos_branch.log)

**however**, a demo made by @fiend#3938 on the discord around version 0.0.9 or 0.0.10 does play normally on stock tf2 and on the beta branch. Here it is: 
[dustbowlbench.zip](https://github.com/mastercomfig/team-comtress-2/files/5235112/dustbowlbench.zip)

I think it is important to retain demo compatibility so we can demonstrate the increase in performance in a controlled test, and demos are the best way to do that.

**Desktop (please complete the following information):**
* Team Comtress version (don't say latest, say the actual version): 0.0.16
* Custom content (if any): none (I've made sure to delete every custom config or content, even steam's cloud backup)
* DX level: default (no launch options)
* Launch options: none except for `-condebug` so I can have the log
* Operating system (OS): Microsoft Windows 10 Pro N 10.0.18363 Build 18363
* Graphics card (GPU): NVIDIA GeForce GTX 1660 SUPER
* Graphics driver version: 26.21.14.4587
* Processor (CPU): AMD Ryzen 5 3600 6-Core Processor, 3593 Mhz, 6 Core(s), 12 Logical Processor(s)
* TC2 on HDD or SSD: HDD
* Memory (RAM) size in MB or GB: 16GB

**Comment by Yttrium-tYcLief** [comment]
fixed with c0c9f3
