### ISSUE TITLE
Missing cryptlib.lib, DK2WIN32.LIB and d3dx9.lib

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [mastercomfig/team-comtress-2#20]
like the title says the read has no mention about this 3 libs that are need for building the engine

**Comment by mastercoms** [comment]
Fixed in https://github.com/mastercomfig/team-comtress-2/commit/d6a0884ca7f32631a39fd639a03651a0b26fad57

**Comment by mtashkinov** [comment]
It looks like I have exactly the same issue.
The `creategameprojects_dev.bat` outputs:

> WARNING: Library '..\..\lib\common\win32\2015\release\cryptlib.lib' does not exist. Adding to project anyway.
WARNING: Library '..\..\lib\common\win32\2015\debug\cryptlib.lib' does not exist. Adding to project anyway.
...WARNING: Library '..\lib\common\win32\2015\release\cryptlib.lib' does not exist. Adding to project anyway.
WARNING: Library '..\lib\common\win32\2015\debug\cryptlib.lib' does not exist. Adding to project anyway.
.....WARNING: Library '..\lib\common\win32\2015\release\cryptlib.lib' does not exist. Adding to project anyway.
WARNING: Library '..\lib\common\win32\2015\debug\cryptlib.lib' does not exist. Adding to project anyway.
.WARNING: Library '..\lib\common\win32\2015\release\cryptlib.lib' does not exist. Adding to project anyway.
WARNING: Library '..\lib\common\win32\2015\debug\cryptlib.lib' does not exist. Adding to project anyway.
................WARNING: Library '..\..\lib\common\win32\2015\release\cryptlib.lib' does not exist. Adding to project anyway.
WARNING: Library '..\..\lib\common\win32\2015\debug\cryptlib.lib' does not exist. Adding to project anyway.
..WARNING: Library '..\..\lib\common\win32\2015\release\d3dx9.lib' does not exist. Adding to project anyway.

And the games.sln build fails with:
>13>------ Build started: Project: engine, Configuration: Debug Win32 ------
8>LINK : fatal error LNK1104: cannot open file '..\..\lib\common\win32\2015\release\d3dx9.lib'
8>Done building project "shaderapidx9.vcxproj" -- FAILED.
10>LINK : fatal error LNK1104: cannot open file '..\lib\common\win32\2015\release\libjpeg.lib'
10>Done building project "replay.vcxproj" -- FAILED.
13>LINK : fatal error LNK1104: cannot open file '..\lib\common\win32\2015\release\binkw32.lib'
13>Done building project "engine.vcxproj" -- FAILED.
9>bsppack.vcxproj -> D:\team-comtress-2\utils\bsppack\.\Debug\.\bsppack.dll
9>Publishing to ..\..\..\game\bin\.
9>        1 file(s) copied.
9>        1 file(s) copied.
11>LINK : fatal error LNK1104: cannot open file '..\..\lib\common\win32\2015\debug\cryptlib.lib'
11>Done building project "server_tf.vcxproj" -- FAILED.
12>LINK : fatal error LNK1104: cannot open file '..\..\lib\common\win32\2015\debug\cryptlib.lib'
12>Done building project "client_tf.vcxproj" -- FAILED.

Did I miss something?
