### ISSUE TITLE
[Enhancement] Raise max thread count

### ISSUE THREAD

**Issue by GamerDude27** [mastercomfig/team-comtress-2#203]
### Description
With PR #141 came the famous https://github.com/ValveSoftware/source-sdk-2013/pull/436 fix, but one thing is missing.
The original poster also additionally proposes raising `MAX_THREADS` and `MAX_TOOLS_THREADS` from 16 to 32, maybe even 64 like in Q3A, so my question is, would this be relevant for TC2?

### Checklist
- [X] None of the open *or* closed issues document this idea.
- [X] This is a new idea, not a bug.
- [X] This idea does not seriously affect game balance.
- [X] This idea is for the code of the game, not for textures, sounds, or other resources.
- [X] This is not an idea for new game content (e.g. new weapons, maps, sounds).
- [X] This is obviously an improvement, not something that people commonly disagree on.

**Comment by maximsmol** [comment]
Some notes:

This might have already been done. I think the max thread count fluctuates between TC2 releases

Until we fix threading this is not gonna give any real performance boost

**Comment by treacherousfiend** [comment]
I think max threads is either unlimited or 32, but right now the game can't really do too much with said threads.

**Comment by mastercoms** [comment]
Maximum threads should be no more than 64 (32 cores when hyperthreading), because threading anything more will break a lot of assumptions about locality because of NUMA nodes.
