### ISSUE TITLE
Rendering Bug on maps added in the Jungle Inferno Update

### ISSUE THREAD

**Issue by TheMostEpicest** [mastercomfig/team-comtress-2#204]
There is a rendering bug on the maps that were added in the Jungle Inferno Update (at least, I have only experienced them there), where white rectangles are drawn in a sphere. See attached photos:

![image](https://user-images.githubusercontent.com/57976441/93417149-2b93af00-f85c-11ea-9808-af047b2f925a.png)
![image](https://user-images.githubusercontent.com/57976441/93417159-32babd00-f85c-11ea-84dd-ccc4b8385834.png)

**Comment by uis246** [comment]
Wait. TC can play with mainline TF?

**Comment by Kenajcrap** [comment]
> Wait. TC can play with mainline TF?

no, you can host a server and play with other people + bots. There have been also playtest sessions in the past

**Comment by mastercoms** [comment]
This was present in TF2 and fixed afterwards, so I don't think this is our bug.
