### ISSUE TITLE
ConTracker uses wrong icon for folders

### ISSUE THREAD

**Issue by TheMostEpicest** [mastercomfig/team-comtress-2#206]
I think this bug may have been introduced in the May 1st update, because previous to that, all of the folder icons were orange, like the Pyroland one is currently. Some of the folders use the grey (locked) icon, when they should be using the orange (unlocked) one. See attached screenshots:

![Screenshot (72)](https://user-images.githubusercontent.com/57976441/93425769-808cf080-f86f-11ea-84ef-9947f23b69f7.png)
![Screenshot (73)](https://user-images.githubusercontent.com/57976441/93425771-81be1d80-f86f-11ea-955b-168ffa42cc81.png)

**Comment by mastercoms** [comment]
We don't have access to source code of the contracker in its final state so we can't really analyze how their specific code causes this bug.
