### ISSUE TITLE
TF2's default Fov settings aren't great.

### ISSUE THREAD

**Issue by OceanMan101** [mastercomfig/team-comtress-2#208]
The default in-game fov settings for new players aren't great, the weapon models are too close to the screen and the fov makes some newer players motion sick and needs some getting used to if you don't know how to change them.

I recommend the following settings to be standard for all new players , whilst still being able to be changed if the user desires:

fov_desired 90

viewmodel_fov 70

**Comment by wgetJane** [comment]
the default value of fov_desired is already set to 90

https://github.com/mastercomfig/team-comtress-2/blob/7d534f243d3f470f563b6559cd968f25180958be/game/client/tf/clientmode_tf.cpp#L141
