### ISSUE TITLE
Allow animations from a different class to play

### ISSUE THREAD

**Issue by AtomicTEM** [mastercomfig/team-comtress-2#209]
### Description
In TF2C they streamlined viewmodels and animations so that every class can other classes animation.

For Example the result of this would be that in randomizer, animations would broken.

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [ ] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).
- [x] This is obviously an improvement, not something that people commonly disagree on.

- [x] This idea has been implemented in vanilla TF2.
- [x] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [x] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [x] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives

1.

**Comment by Yttrium-tYcLief** [comment]
This requires substantial asset work (to standardize bones) and most likely falls outside the scope of this project.

**Comment by treacherousfiend** [comment]
iirc bones are already pretty standardized, name wise at least, but I'd need to do more research

**Comment by Yttrium-tYcLief** [comment]
Attachment points (which are bones) are not standardized inter-class, only intra-class.

**Comment by treacherousfiend** [comment]
fair enough, I could put in the effort to do that, but its not really a problem that needs fixing.

**Comment by Yttrium-tYcLief** [comment]
Again, it's not that it couldn't be done - they obviously did it - it's just that it falls outside the scope of this project. We're focused on bugs, optimizations, and *minor* QoL, *without* reworking major game systems (unless it's purely for performance).

**Comment by treacherousfiend** [comment]
yeah, thats why I said its not really a problem
