### ISSUE TITLE
Better dual monitor support

### ISSUE THREAD

**Issue by ticktackk** [mastercomfig/team-comtress-2#21]
**Is your feature request related to a problem? Please describe.**
Currently when playing Team Fortress/Comtress 2 with dual monitor setup and ~flicking~ swiping mouse too fast causes mouse to go over the other screen and cause weird frame drops and if accidently clicked when the focus is lost, TF2 will minimize.

**Describe the solution you'd like**
A better support dual monitor 👍🏼 

**Describe alternatives you've considered**
Currently using Dual Monitor Tools to lock cursor to the active monitor when playing TF2.

**Additional context**

**Comment by Yttrium-tYcLief** [comment]
Does this still happen as of 0.0.15?

> Optimized mouse calculations
> - Mouse no longer locked to center of screen per frame, instead it is bounded within the window passively
> - This was happening twice (now not at all) due to a bug in how VGUI updated the mouse
> - This should also fix issues with the mouse leaving the window on multi monitor set ups
> - Cached window offset so that a transformation from window to screen is not needed

**Comment by Residays** [comment]
> Does this still happen as of 0.0.15?
> 
> > Optimized mouse calculations
> > 
> > * Mouse no longer locked to center of screen per frame, instead it is bounded within the window passively
> >   -- This was happening twice (now not at all) due to a bug in how VGUI updated the mouse
> >   -- This should also fix issues with the mouse leaving the window on multi monitor set ups
> > * Cached window offset so that a transformation from window to screen is not needed

Not on my end.
