### ISSUE TITLE
4K resolution text scaling error.

### ISSUE THREAD

**Issue by asdasdasdasda-pixel** [mastercomfig/team-comtress-2#213]
### Description

This bug is a text scaling error directly related to the resolution currently in use. Certain text boxes, like the server browser, settings box, or command console will not scale properly in higher resolutions. 4K displays in particular, when set at their native resolution, will have these text boxes render absolutely tiny. Other text boxes, such as ones displayed by Mann Co. Store, or the Matchmaking menus do not have this issue.
The scaling issue is not only a 4K problem, but doesnt scale properly in any resolution. However it is not obvious at regular resolutions, like 1920. I believe the text in these boxes are always set to be a certain size (IE 20 pixel font size), and stay this way regardless of the resolution. Higher resolution means more pixels being displayed, which means smaller average text box.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the lastest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

To reproduce, increase resolution in video settings, and then measure the settings box to the rest of the screen. The higher the resolution, the more obvious the bug.

### Setup Details
N/A

### Performance Details
N/A

**Comment by Yttrium-tYcLief** [comment]
This is an inherent issue with Source, where SDK-styled panels are not scaled whatsoever. This applies to the console, demoui, options menu, server browser, etc.

HUDs can *somewhat* work around this, but it isn't clean.

This *might* be fixable without substantial code rewrites, but it might not be. Need to wait for someone more familiar with the situation to comment on that.

**Comment by Yttrium-tYcLief** [comment]
Mastercoms has stressed that this is a priority issue so I'm going to remove the rfc and just say it's within scope.

**Comment by mastercoms** [comment]
I'll be taking a look at this soon.

**Comment by mastercoms** [comment]
Fixed internally.
