### ISSUE TITLE
[MVM] Big list of bugs + suggestions at the end

### ISSUE THREAD

**Issue by ZaeZaeCactus** [mastercomfig/team-comtress-2#218]
I was asked to post my list of broken things in MVM as an issue via github, so I decided to give it a shot.
Sorry if this list is too big, my first time posting on git, so not really sure of the proper posting etiquette here
The first section is dedicated to major bugs/inconsistencies in the mode, while the second half is mainly just game mode suggestions from the views of somebody who's been playing the mode since 2012

===================================
======Bugs in Mann Vs. Machine=====
===================================
 
 
=======Fix Medicbot’s Ubercharge not working properly when going out of the spawn=====
 
Robots are under the “TF_COND_INVULNERABLE_HIDE_UNLESS_DAMAGED” condition when in their func_respawnroom (only making them appear as Ubercharged when attacked). If an Uber Medic uses his Ubercharge when in the robot spawn (when his patient health is low), he will not stay Ubercharged (but his patient will). This is mostly problematic on Bigrock, where this can be done easily due to the robot not dropping down from their spawn.

======Medic Robots will overheal each other if squad is too big======
This is most noticeable on Metro Malice Wave 1 with the Giant Crit Soldier +12 Uber Medic Combos at the end of the wave
Med Bots will spread overheal to each other, making them more likely to not drop from things like sticky traps and Explosive Headshot
 
===============Fix Penetration upgrades not penetrating shields=========================
 
This isn’t really a problem in official missions since robots do not have penetration upgrades and there’s no shield Medics, but the latter is used commonly in custom MvM missions. Right now, the only way to make the penetration upgrade go past the shield is by having a robot/player between the shooter and the shield.
 
===== Burn Upgrades ======
 Burn Duration does not actually affect the burn time of fire weapons
 
Also, consider renaming the upgrades to "afterburn damage/duration"
Right now many new players think this affects the direct damage of your flamethrower.
 
======Money in Robot Spawn====
Money piles dropped off-limit into robot spawn cannot be collected (noticeable on bigrock)
money dropped in spawn should be auto-collected like red-money
 
 
========Fix the Vaccinator consuming two Ubercharge portions when reviving a player ========
 
The Vaccinator tends to be underused in MvM for various reasons, but the fact that it sometimes “wastes” an Ubercharge when reviving a player is a big one. If you revive a player a bit with healing then use your Ubercharge, the first charge will revive the player and a second one will be used immediately after to apply a resistance bubble on the already revived patient. This divides the reviving ability of the Vaccinator by two. A possible solution is to have the patient receive a resistance bubble when revived and before the second charge is used.
 
========Fix the Uber Duration upgrade not working on the Vaccinator’s bubbles========
 
As of the Gun Mettle update that changed the Vaccinator Ubercharge to deploy a status condition bubble instead of a real Uber, the Vaccinator’s Uber Duration upgrade has no effect, no matter how many points are purchased; deployed resistance bubbles always have a duration of 2 seconds.
======Fix the Spy being unable to use his Sapper after sapping a building
 
Spy is really effective against set-up Engineers, but is hindered by a design oversight. If the Spy saps an Engineer’s building, his Sapper is on cooldown until the building or the Sapper is destroyed. This prevents Spy from sapping multiple buildings like in PvP and there’s no real reason he shouldn’t be able to do so.
 
=====Scout Cash Collection=====
Scout Cash magnet has a glitchy mechanic where the money will circle around the scout for a second before he collects it. This can cause the money being collected to get stuck on map props like rocks, and never get collected.
It might be better to just disable the magnet circle mechanic. Sigsegv has a mod that does it with source code:
https://www.youtube.com/watch?v=forcTzIQSKo
 
====Unintended Ready up timer reset abuse====
Reconnecting to a server will cause the countdown to reset and can easily be used to grief. This includes
- Switching to spectator
- Leaving the game as a spectator
- Leaving the game as red
- Using the "retry" command
 
====Common Robots are immune to Holiday Punch ===
Non-Giant Robots are immune to the holiday punch's laugh due to animation issues.
This can be fixed by having the robots use player animations for the laugh taunts, like in this Sig Video:
https://www.youtube.com/watch?v=Ps-vIf0gUUg
 
====Giant Robots do not properly target players====
This can be fixed by giving Miniboss robots the melee ai sub type.
Extremely important fix needed to make giant robots rely less on tunnel vision and effectively fight back ambushers and "body blockers".
Melee AI already picks targets based on proximity. No significant programming needed as this behavior can simply be ported over to AI regardless of its equipped weapon (Giants will still use their minigun/rocket launcher like normal)
 
===GM Switch breaks robots===
Ever since Gun Mettle's universal weapon switch buff (0.67 to 0.50), Bots with items such as Bonk! Atomic Punch or Soldier Banners will often attempt to switch to it, but will be stuck in a endless loop of switch as the AI calculates the old speed. Most noticeable with giant Banners on Rottenburg or giant bonks on Mannhattan.
 
===Giants do not resist knockback properly====
https://www.youtube.com/watch?v=2pd0VF-PY7A
 
Valve attempted to fix this, and then broke it again during Jungle Inferno. Clearly a glitch, and not a balance design
 
===Robot AI do not ignore stock watch cloak====
Robot AI will detect a spy cloaking even if they are already disguised. Inconsistency as they do not get alerted from the Dead Ringer cloak
 
====Scout bats are missing "Mark-On-Hit" for all bat weapons====
For some reason this is only available on the sandman. Strange inconsistency
 
====Giants do not properly resist airblast====
Jungle Inferno airblast is too strong, and the giant's pre-baked knockback resistance doesn't really work against it.
(possibly could just remove airblast strength, as its already really strong vs. robots anyway)
https://youtu.be/1vAxPBByhsc
 
====Demoknight non-swords cannot get damage upgrades====
Currently when you equip a shield, only "sword" type weapons can get damage upgrades.
This is a strange inconsistency, since weapons like the bottle cannot benefit from a melee playstyle and make them inferior to swords
 
====Loose Canon Damage Upgrade====
Damage upgrades on the Loose Canon do not affect the impact of the canon ball, only the explosion
 
===Short Circuit Firing speed===
Right now, firing speed on the Short Circuit only affects it's primary fire, and not the energy ball.
 
====Disposable Sentry====
Right now, the disposable Sentry does not benefit from engineer's building upgrades, like firing speed or health. 
Weird inconsistency that makes the disposable sentry even more of a burden
Disposable also cannot have it's ammo refilled since it uses old gunslinger code (iirc)
 
====Huntsman has really poor damage rounding===
https://steamcommunity.com/app/440/discussions/1/35222218865758497/
 
===================================
=Suggestions for Mann Vs. Machines=
===================================
Replace Gas Passer's Explode on Ignite with Milk/Jarate's slow on hit upgrade
-Explode on Ignite is way too strong, and actively hurts the mode. Slow on hit will still give pyro some utility, while not making things too insane
Refund is only allowed in teams of 5 or less
-Prevents the refund mechanic from being abused to min/max waves, while still allowing struggling teams to have a fighting chance
Reanimators are now a body upgrade the patient must buy.
-Reanimators are an extremely powerful ability that is part of the reason many players refuse to play without a Medic.
-Reanimators completely remove the ability for robots to stand a chance and push through very skilled teams.
-While reanimators are admitedly an interesting ability, it must be locked behind money. Each reanimator should be a buyable powerup,       rather than a universal limitless ability
Weapons no longer have a dynamic upgrade limiter (such as Direct Hit & SkullCutter having only 3 damage upgrades
-Encourages loadout variety. Most weapons that have these already have extreme drawbacks that justify the extra stats (like DH's lower splash)
Standardized Buyback cost to 100$
-Buybacks deemed too inexpensive/cheap for their usefulness and game-saving power, increased overall cost although it no longer scales with the time left.
Canteen is no longer forced / constantly messaged about (back to before)
-Small ease-of-life change to disable the game constantly nagging players about equipping the Canteen with HUD messages.
-Fixes issue with custom maps where the Grapple Hook is being overriden by Canteen.
-Players may get to keep their Duck Journal or Spellbook equipped free of spam
Adjust canteen prices 
- Critical   200$
- Ubercharge  200$
- Ammo Refill  25$
- Teleport   5$
- Building   150$ 
-Greatly increased prices for most canteens
-With critical canteen being able to allow a single player to destroy one to multiple giants at once and considerably damage tanks, this canteen makes what should be the burden of 6 players trivial and sees its price reflected as such.
-The ubercharge canteen is effectively just as potent as a critical canteen in the hands of certain classes that do not suffer from reloads, such as heavy, pyro and spy. Increased price to match that of the critical canteen.
-Considerably lowered teleport canteen price as a way to turn it into a multi-purpose canteen and a low cost sink.
-increased building canteen cost as it is effectively the engineer's "best" canteen comparable to critical/ubercharge in strength and usefulness
Revert MVM specific YER nerf
-Your Eternal Reward does not grant a disguise on kill until after a 1.5 second delay
-This has been un-nerfed in potato.tf's testing servers, and it does not negatively affect game balance in anyway.
Engineer Robot's airblast has its size reduced to the very diameter of a building, being effective only at the specific spot selected
-Right now, engineer robot airblast is a little larger than an explosion. Very disruptive to gameplay, this change will make them less annoying, while still prevent players getting trapped.
Mantread/Jetpack stomp deals x10 damage to "miniboss" robots instead of x3
-Stomping is too low damage to really be worth it. Will hopefully make it slightly more competitive with other secondaries
Bullet/Blast resistance now costs $400 from $300
-These upgrades are considered "do or die" compared to it's contemperaries, while making medic feel a bit more redundant. This change puts them on par with damage upgrades
Give certain Secondary weapons "crit on kill" upgrades ($400)
-Guillotine, shotgun, flare guns would get this attribute
Decrease Destroy projectile price to $150/tick
-Destroy Projectile is rather pointless due to resistance upgrades. This change would make it more competitive
Remove damage penalty for knockback rage
-Knockback Rage has a hidden -50% damage penalty while active. This makes the upgrade a joke in the MVM community, and is a waste of money
Give Heavy fists "minicrits become crits" upgrade
-Give Steak some utility, and gives heavy a way of dealing with tanks
Give Pain Train money collection radius
-Useless weapon right now, gives it some utility. Money will not heal you
Give Medic Melees "mark on hit" upgrade ($100)
-would not include ubersaw
Nerf Explosive Headshot, but give rifles the Third Degree's Hit Connected by Healbeam as an upgrade 
-Reduce explosive headshot damage to 75, but new upgrade allows sniper to reliably kill medic robots
Give Revolvers Damage upgrades
-4 upgrades of +25% damage bonus $250/tick
 
New Expert Rules:
- Canteen disabled
- Reanimator Upgrade disabled
- Buyback disabled
- Sniper bots can headshot
- Bombs grant all buff levels instantly to any bot carrying it (giants still excluded)
- Sentry Buster explosion no longer affects fellow robots

**Comment by Yttrium-tYcLief** [comment]
Hoookay.

First off, we don't accept suggestions for balance. This project is completely focused on optimization, bugfixing, and small QoL additions. Balance is not QoL.

Secondly, please submit a separate issue for each bug. It's infinitely easier for us to track and work on them that way.

Thirdly, the medic uber bug will be fixed in #129, and the the money in robot spawn was fixed in #110, so those are duplicates and should not be posted. Spy sapping was determined to be balance and therefore out-of-scope in #197. Mark on death upgrades are considered balance. Scout instant collection was determined out-of-scope in #124.

In fact, *most* of these would be considered out-of-scope, but feel free to post them and have them judged individually.
