### ISSUE TITLE
Strange decorated weapons do not glow while ubercharged.

### ISSUE THREAD

**Issue by PseudoCoffee** [mastercomfig/team-comtress-2#220]
### Description
Pretty self explanatory, any decorated weapon that is also strange(it has the strange counter attached) will not become ubercharged in the first person model while the player's hands will.

### Reproduction
Equip any strange and decorated weapon and get ubercharged or use "addcond 5" command.

**Comment by Yttrium-tYcLief** [comment]
Have you confirmed this is the case in TC2 as well, or just live TF2?

**Comment by PseudoCoffee** [comment]
Live tf2 only.

**Comment by micwoj92** [comment]
> Live tf2 only.

You should fill in the issue template and if not sure ALWAYS check if issue persist in TC2 as with every day passed there are more changes.

**Comment by Yttrium-tYcLief** [comment]
If this bug only occurs with live TF2 and does not exist in TC2, there's nothing we can really do then.

Not to mention it's *likely* an issue with material files, which are assets, which we don't touch.
