### ISSUE TITLE
The short circuit right alt-fire is not showing the orb at all.

### ISSUE THREAD

**Issue by Boshikuso** [mastercomfig/team-comtress-2#230]
### Description
pretty self explanatory. The particle orb thing just will not show.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the lastest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. just alt fire the weapon lol

### Screenshots
n/a unless u just wanna see a short circuit lol

Setup Details
Server or client: client
Operating system: windows 10
Team Comtress version: 0.0.16
Custom content: nope, fresh install of tc2
Launch options: none
Graphics driver: 3.20.4.14
DirectX level: dx 10
Performance Details
GPU model: NVIDIA GTX 1070 gaming
CPU model: AMD RYZEN 7 1700
RAM amount: 64GB
TF2 installed on: HDD
TC2 installed on: HDD
TC2 installation method: Basic

**Comment by micwoj92** [comment]
this is because it is pre jungle inferno, invalid

**Comment by Margen67** [comment]
You need to make it like this for it to show up checked:
`[x]`

**Comment by Yttrium-tYcLief** [comment]
I edited your post to fix the checkboxes.

This is a bug with TC2 because the Short Circuit was changed in Jungle Inferno and was unfinished at the time of the leak we're using. As such, this is an out-of-scope bug and will not be fixed.

**Comment by micwoj92** [comment]
> I edited your post to fix the checkboxes.
> 
> This is a bug with TC2 because the Short Circuit was changed in Jungle Inferno and was unfinished at the time of the leak we're using. As such, this is an out-of-scope bug and will not be fixed.

The orb was actually added in 2018 according to tf2 wiki

**Comment by Yttrium-tYcLief** [comment]
Sorry. Yes, it was updated to the modern behavior with Blue Moon, but my guess is they were testing those changes with the current build. Either way, it's out-of-scope, since it's not core to testing.

**Comment by Boshikuso** [comment]
Okay, good to know. Hopefully it doesn't break the orb when the update is officially supported lol

**Comment by Boshikuso** [comment]
should i bother making a post about how the medigun and kritzkrieg have no healing audio? @Yttrium-tYcLief

**Comment by micwoj92** [comment]
> Okay, good to know. Hopefully it doesn't break the orb when the update is officially supported lol

what update? I think you are getting confused here.

**Comment by treacherousfiend** [comment]
It won't, coms isn't just going to send the entire build (for several reasons including this), but we have no reason to touch short circuit so no changes.

**Comment by Boshikuso** [comment]
I'm on most recent build, just tested and its not present

**Comment by micwoj92** [comment]
> should i bother making a post about how the medigun and kritzkrieg have no healing audio? @Yttrium-tYcLief

This has been supposedly resolved and will be included in next release.
https://github.com/mastercomfig/team-comtress-2/pull/212

**Comment by treacherousfiend** [comment]
its fixed as of commit d77d41c

**Comment by Boshikuso** [comment]
Excellent! you guys are so quick, i love it

**Comment by micwoj92** [comment]
> I'm on most recent build, just tested and its not present

Build git

**Comment by treacherousfiend** [comment]
the public builds are not the most recent, they just are when coms decides to actually call it a release

**Comment by Boshikuso** [comment]
That's understandable

**Comment by Boshikuso** [comment]
So offtopic... you think valve will ever adopt this for real? I personally got a 200+ fps boost. I need this in my life.

**Comment by Yttrium-tYcLief** [comment]
> Okay, good to know. Hopefully it doesn't break the orb when the update is officially supported lol

The work being done in this project, assuming Valve will be open to the idea, will be pulled *forward*. They will not simply switch to our branch.

>should i bother making a post about how the medigun and kritzkrieg have no healing audio?

This was fixed in #212, there just hasn't been a release that included it yet.

**Comment by treacherousfiend** [comment]
offtopic should probably be done in the discord, not here

**Comment by micwoj92** [comment]
> So offtopic... you think valve will ever adopt this for real? I personally got a 200+ fps boost. I need this in my life.

@Yttrium-tYcLief please lock this and limit to collaborators to prevent even more spam. For such question the discord should be used.
