### ISSUE TITLE
Raising the voice quality to 48kHz sampling

### ISSUE THREAD

**Issue by CoolJosh3k** [mastercomfig/team-comtress-2#240]
### Description
Raise the voice sampling rate to the 48 kHz limit that CELT allows.
Also upgrading to using Opus instead would be nice.

**Comment by Thestickman391** [comment]
This seems out of scope for this project

**Comment by maximsmol** [comment]
I think this would be fine to do, but this is up to coms

**Comment by CoolJosh3k** [comment]
I went through the new checklist for a feature request and all was good.

I am hoping that changing the limit is something simple, while switching to Opus would maybe be more complex?

**Comment by GreenSwede** [comment]
There is no benefit to go up from 44khz to 48khz, you're not going to notice any difference. It's just going to cause unnecessary extra bandwidth to be sent.

**Comment by melvyn2** [comment]
> There is no benefit to go up from 44khz to 48khz, you're not going to notice any difference. It's just going to cause unnecessary extra bandwidth to be sent.

I think tf2 uses 24kHz:
`voice_init using steam voice optimal sample rate 24000`

**Comment by GreenSwede** [comment]
> > There is no benefit to go up from 44khz to 48khz, you're not going to notice any difference. It's just going to cause unnecessary extra bandwidth to be sent.
> 
> I think tf2 uses 24kHz:
> `voice_init using steam voice optimal sample rate 24000`

```
"sv_voicecodec" = "vaudio_celt_high" ( def. "steam" )
 - Specifies which voice codec to use. Valid options are:
vaudio_speex - Legacy Speex codec (lowest quality)
vaudio_celt - Newer CELT codec (22kHz, 22kbps)
vaudio_celt_high - Newer CELT codec, higher bitrate (44kHz, 44kbps)
steam - Use Steam voice API
```

**Comment by melvyn2** [comment]
> > > There is no benefit to go up from 44khz to 48khz, you're not going to notice any difference. It's just going to cause unnecessary extra bandwidth to be sent.
> > 
> > 
> > I think tf2 uses 24kHz:
> > `voice_init using steam voice optimal sample rate 24000`
> 
> ```
> "sv_voicecodec" = "vaudio_celt_high" ( def. "steam" )
>  - Specifies which voice codec to use. Valid options are:
> vaudio_speex - Legacy Speex codec (lowest quality)
> vaudio_celt - Newer CELT codec (22kHz, 22kbps)
> vaudio_celt_high - Newer CELT codec, higher bitrate (44kHz, 44kbps)
> steam - Use Steam voice API
> ```

Ah ok, thanks for clearing that up.

**Comment by CoolJosh3k** [comment]
Looking into it more...

- sv_voicecodec does default to use the Steam voice.
- Mathmaking servers do not publicly report their sv_voicecodec value or their sv_use_steam_voice value.
- According to the patch notes on December 21, 2016, CELT was made the default.

I presume that the default is overridden via a cfg file on matchmaking servers. Does it use celt or celt_high though? I am assuming it is set to the 22kHz version.

I also found a "product update" (16 Jun, 2017) that tells server operators to use the 22kHz version: https://store.steampowered.com/news/30120/

I should imagine going from 22kHz to 48kHz would make quite a difference.

As I understand it 48kHz is the good standard for modern digital audio and used all over the place.

Feel free to correct me or add more information. :)

**Comment by mastercoms** [comment]
The default is vaudio_celt, and Jill said this was intentional, with vaudio_celt_high being an option for community servers if they wanted.
