### ISSUE TITLE
Screenshot bug

### ISSUE THREAD

**Issue by joshuadinada** [mastercomfig/team-comtress-2#245]
_Ingame_, if you press F7 or whatever button is binded to "Take Steam Abuse screenshot", the game becomes unplayable, with many visual bugs, leaving you with the only option to restart the game. This also happends if you take a normal screeshot.
Here is demonstration of the bug: https://youtu.be/mAL8SRU1kNg

**Comment by Yttrium-tYcLief** [comment]
We need far more info than this. Please fill out the New Issue template rather than deleting it.
