### ISSUE TITLE
Screenshots not functioning proprely

### ISSUE THREAD

**Issue by joshuadinada** [mastercomfig/team-comtress-2#246]
### Description
Ingame, if you press F5 or whatever button is binded to "Take screenshot", the game becomes unplayable, with many visual bugs, leaving you with the only option to restart the game. This also happends if you take a  Steam Abuse screenshot.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the lastest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Join a game
2. Press the screenshot button

### Screenshots

![Immagine 2020-09-19 151136](https://user-images.githubusercontent.com/71554143/93668060-78f56380-fa8a-11ea-9b5b-da2a5968167b.png)

### Setup Details
- *Server or client:*  Game Client
- *Operating system:*  Windows 10
- *Team Comtress version:*  0.0.17
- *Custom content:*  No.
- *Launch options:*  No.

- *Graphics driver:* 
- *DirectX level:* 90

### Performance Details

- *GPU model:* 
- *CPU model:* 
- *RAM amount:* 
- *TF2 installed on:* 
- *TC2 installed on:* 
- *TC2 installation method:*

**Comment by Yttrium-tYcLief** [comment]
![hl2_2020-09-19_11-00-45](https://user-images.githubusercontent.com/1037011/93670192-7e8d8200-fa67-11ea-87e2-1dbb306b5110.jpg)

haha okay yeah that's a problem
