### ISSUE TITLE
cl_interp should be locked at lowest

### ISSUE THREAD

**Issue by joshuadinada** [mastercomfig/team-comtress-2#250]
### Description

Often, in vannilla tf2, cl_interp is raised (usually to 5) and abused to get long-distance backstabs with spy. I propose, for matches with sv_cheats 0, to lock it at 0.

### Checklist

- [ ] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This is not an idea for new game content (e.g. new weapons, maps, sounds).
- x ] This is obviously an improvement, not something that people commonly disagree on.

- [ ] This idea has been implemented in vanilla TF2.
- [x] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

**Comment by wgetJane** [comment]
cl_interp no longer exists in tc2 (replaced with cl_interp_ratio)

max unlag has also been decreased to 0.2 seconds from 1 second in tc2
