### ISSUE TITLE
Resizing causes game crash.

### ISSUE THREAD

**Issue by joshuadinada** [mastercomfig/team-comtress-2#251]
### Description

When you resize the game resolution (to any resolution) the game crashes. When you restart the game the resolution has been changed

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Go to settings and click on the "Video" section
2. Change the resolution.

### Setup Details
- *Server or client:*  Client.
- *Operating system:*  Windows 10
- *Team Comtress version:*  0.0.17
- *Custom content:*  None.
- *Launch options:*  None.
- *DirectX level:*  90

**Comment by Yttrium-tYcLief** [comment]
By "resize" do you mean change the game resolution, or literally clicking and dragging on the window?

**Comment by joshuadinada** [comment]
I re-installed the mod and it stopped giving me problems. Sorry for the trouble

**Comment by Yttrium-tYcLief** [comment]
No worries, glad you got it sorted.
