### ISSUE TITLE
hl2.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by higgy999** [mastercomfig/team-comtress-2#252]
### Description

This is an extension for #247. I have no idea what the issue might be. I have rebuilt the solution, verified the TF2 installation and copied them over but I can't seem to be able to find the issue. This only occurs when running the client. Any help would be appreciate!

"hl2.exe - Entry Point Not Found
The procedure entry point SteamDatagramClient_Init_Internal could not be located in the dynamic link library
/game/tf/bin/client.dll."

"Engine Error
Could not load library client. Try restarting. If that doesn't work, verify the cache."

### Checklist

- [X] None of the open *or* closed issues document this problem.
- [X] This is a bug, not a new idea.
- [X] This is objectively a bug, and not something that people commonly disagree on.
- [X] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [X] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [X] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Build the solution
2. Running the Local Windows Debugger with Client (TF)

### Screenshots

![Annotation 2020-09-19 095736](https://user-images.githubusercontent.com/12685323/93679969-93741080-fa7b-11ea-8074-fc4282c5b5e2.jpg)
![Annotation 2020-09-19 133614](https://user-images.githubusercontent.com/12685323/93684001-34170000-fa7d-11ea-8f88-9c53c0281101.jpg)

### Setup Details
- *Server or client:* Client
- *Operating system:* Windows 10
- *Team Comtress version:* e840a6c
- *Custom content:* None
- *Launch options:* -steam -game tf -insecure -novid -nojoy -nosteamcontroller -nohltv -particles 1 -noborder -particle_fallback 2 -dev -allowdebug

**Comment by maximsmol** [comment]
Are you using the `steam_api.dll` and `steamnetworkingsockets.dll` that come with TC2 (these are in `game_clean`)? Live TF2 versions will not work.

**Comment by higgy999** [comment]
> Are you using the `steam_api.dll` and `steamnetworkingsockets.dll` that come with TC2 (these are in `game_clean`)? Live TF2 versions will not work.

I was not. Thanks I fixed it!
