### ISSUE TITLE
Unable to call for help/medic

### ISSUE THREAD

**Issue by joshuadinada** [mastercomfig/team-comtress-2#263]
### Description

Ingame, if you press the button to call MEDIC!, nothing will happend. I tried binding it to diffrent keys with no result. I also tried adding a medic bot to my team, yet still nothing happend.
**Edit: for those who are having this same problem, open console and type** ` bind e "voicemenu 0 0"`
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Go in a match and press "e"

### Setup Details
- *Server or client:*  Client.
- *Operating system:*  Windows 10
- *Team Comtress version:*  0.0.17
- *Custom content:*  None.
- *Launch options:*  None.
- *DirectX level:*  90

**Comment by Yttrium-tYcLief** [comment]
fixed over discord, was related to persistent config files from live tf2 installation

for users experiencing this: run the game with `-default`, then type `host_writeconfig` ingame, then close the game and delete any `tf/cfg/autoexec.cfg` you might have.

**Comment by mastercoms** [comment]
I think this bug should still be open, given that the options menu will rebind it to the Jungle Inferno command `+helpme` instead of the old `voicemenu 0 0`. We should look into either implementing `+helpme` or changing it back to `voicemenu 0 0`.

**Comment by mastercoms** [comment]
Fixed in https://github.com/mastercomfig/team-comtress-2/commit/102883ce975661480292b1a3a76074ca119eb7ae
