### ISSUE TITLE
[MVM] Upgrade Shop has JI upgrades for all weapons

### ISSUE THREAD

**Issue by DrCactusTF2** [mastercomfig/team-comtress-2#267]
### Description
When you open the upgrade shop, every class/weapon has the upgrade stats used for the new mvm upgrades added to the gas passer + jetpack for jungle inferno
This causes many weapons to have too many upgrades and prevent you from buying ones like Health On Kill on the Rocket Launcher, and you cannot access the "cancel" button at all because of the overlap

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. Open the shop as any class

### Screenshots
https://steamuserimages-a.akamaihd.net/ugc/1638704307080674982/0FE89EC88947F0256F4E43C25052613EE6B9F0AB/

### Setup Details
- *Team Comtress version:* 0.0.17

**Comment by int-72h** [comment]
This really does show that the leak was mid-JI.
It shouldn't be more than an alteration to the shop list (which is a text file somewhere, iirc) though.

**Comment by Thestickman391** [comment]
Should be closed as of 8bd88e80b869c07552e71feaea65616305c217e0
