### ISSUE TITLE
Fall damage "lines" not playing

### ISSUE THREAD

**Issue by joshuadinada** [mastercomfig/team-comtress-2#275]
### Description

When you take fall damage, no "moan" is reproduced by the class: a bone-braking noise is played instead. 
#241 pointed out this problem, but with spy's disguises.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Take fall damage

### Setup Details
- *Server or client:* client.
- *Team Comtress version:*  0.0.17

**Comment by maximsmol** [comment]
We should make it so only *other* players do the `hurt a lot` response and the local player does not, otherwise this will make e.g. rocket jumping a lot more annoying

**Comment by joshuadinada** [comment]
> We should make it so only *other* players do the `hurt a lot` response and the local player does not, otherwise this will make e.g. rocket jumping a lot more annoying 

You could mabe add a command for enabling/disabling those sounds (ex. `tf_enable_falldamage_sounds` )

**Comment by agrastiOs** [comment]
This is in live TF2 since Jungle Inferno.

**Comment by melvyn2** [comment]
> This is in live TF2 since Jungle Inferno.

Do we not fix live tf2 bugs anymore? Why close this?

**Comment by mastercoms** [comment]
I mean, this might be an intended change.

**Comment by agrastiOs** [comment]
@melvyn2 Perhaps I needed to word this more clearly: live TF2 has made it so that classes make the pain sound if fall damage is received on the Jungle Inferno Update. They have also changed the fall damage sound to be more crunchy. As this is already "fixed" in live TF2 and it was a change in JI, it's not in the scope of the project to bring JI features to TC2.
