### ISSUE TITLE
Add support for more mouse buttons

### ISSUE THREAD

**Issue by henriquecm** [mastercomfig/team-comtress-2#277]
### Description
Currently TF2 only has support up to Mouse5, but it's uncommon for gamer mouses to have up to 9 buttons.

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).
- [x] This is obviously an improvement, not something that people commonly disagree on.

- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives
I don't see a alternative of implementing this

**Comment by joshuadinada** [comment]
An easy fix would be using an other program to bind the different mouse buttons to keys, and then binding those keys to functions.

**Comment by Yttrium-tYcLief** [comment]
Implementing Mouse6-Mouse9 as well as F13-F24 would be ideal, for the full range of macro capability.

**Comment by Yttrium-tYcLief** [comment]
implemented in #356 (779e624)
