### ISSUE TITLE
Add file which mentions all removed and added cvars

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/team-comtress-2#28]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I type a command in console, but it does not exist in TC2

**Describe the solution you'd like**
A file named "readmecvars.md" or something like this which mentions all removed and added cvars

**Describe alternatives you've considered**
.

**Additional context**
n/a

**Comment by Knucklestf** [comment]
We could in theory uncomment this line https://github.com/mastercomfig/team-comtress-2/blob/639a3c5ca3c73a8845d5fcaf13625f5fe862442b/external/vpc/tier1/convar.cpp#L28

Then use the FCVAR_DEVELOPMENTONLY flag for any console commands that are deprecated and set their help text to something like "Command removed in this build of Comtress. Replaced by ______"

However, I'm not sure if there is a way to make the command print its help text whenever it is ran even if it is given a value

**Comment by mastercoms** [comment]
external/vpc is not used. development cvars are already enabled in their proper place

**Comment by micwoj92** [comment]
Partially fixed in https://github.com/mastercomfig/team-comtress-2/commit/2060d8f1925c076832c5a375e0c62f5427444dc2

**Comment by Margen67** [comment]
https://github.com/mastercomfig/team-comtress-2/wiki/New-console-commands-and-launch-options
https://github.com/mastercomfig/team-comtress-2/wiki/Edited-and-removed-console-commands

**Comment by micwoj92** [comment]
Thank you, wasn't aware of recent changes.
