### ISSUE TITLE
Minimum Casual Level to Play Comp

### ISSUE THREAD

**Issue by MysticTutor** [mastercomfig/team-comtress-2#283]
### Checklist

- [yes] None of the open *or* closed issues document this idea.
- [yes] This is a new idea, not a bug.
- [yes] This idea does not seriously affect game balance.
- [yes] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This is not an idea for new game content (e.g. new weapons, maps, sounds).
- [ ] This is obviously an improvement, not something that people commonly disagree on.

- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives

1.

**Comment by DrCactusTF2** [comment]
You need to use the description to describe what you're suggesting/reporting

**Comment by wgetJane** [comment]
this is out of scope
also, please write in a description
