### ISSUE TITLE
Vote on class of bot in comp

### ISSUE THREAD

**Issue by MysticTutor** [mastercomfig/team-comtress-2#284]
### Description

If a team in competitive is give a bot the team should be able to vote on what class that bot should be.

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This is not an idea for new game content (e.g. new weapons, maps, sounds).
- [x] This is obviously an improvement, not something that people commonly disagree on.

- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives

1.

**Comment by maximsmol** [comment]
Does the TC2 version of the game even have competitive? Like, it obviously does not works since there are no servers, but do we even have the gamemode code?

**Comment by Yttrium-tYcLief** [comment]
There is competitive, as it was introduced in Meet Your Match, but the competitive code received a major overhaul in Blue Moon, and this is likely out of scope anyway.

It's a neat feature request but not really the kind of thing this project is focused on. May revisit in the future, though, if our scope expands.
