### ISSUE TITLE
Current Installation instructions do not take into account possible issues with Steam Cloud Sync

### ISSUE THREAD

**Issue by Kenajcrap** [mastercomfig/team-comtress-2#295]
### Description

If you have Cloud Sync enabled and follow the current instructions, the original TF2 `config.cfg` that got deleted during the installation will be restored in TC2 when it is first launched, which, depending on the user's TF2 config, may cause crashes or other weird problems, and also will make troubleshooting harder since the user would not be wrong to affirm with 100% certainty he deleted his config.cfg like instructed.
This leads to even worse problems if the user does turn cloud sync off before launching TC2 for the first time but turns it back on later on, which would either update TF2's `config.cfg` or TC2's `config.cfg` depending on in which order he plays the different versions after cloud sync is turned back on, leading to a lot of confusion and aggravation if an unaware player loses his TF2 config "because of TC2" (not actually tc2's fault)
The short term solution would be to include instructions to disable cloud sync and keep it disabled while they have TC2 "installed". But I feel like this is the kind of instruction that will get ignored (because they think they know better) or be forgotten by users after a while.

### Checklist

- [x] None of the open *or* closed issues document this idea.

### Alternatives

1. Finding a way to check if cloud sync is enabled for TF2 and preventing TC2 from launching if it is
2. Finding a way to disable cloud sync entirely for TC2 but keep it enabled when launching TF2

**NOTE:** My initial theory (that was shared by some others on discord) was that TC2 had cloud sync disabled but for some reason it was enabled only on the first launch, I tested many scenarios and that doesn't seem to be the case. TC2 follows TF2's cloud configuration and behavior normally. I can expand on that if it is pertinent to do so.

**Comment by Yttrium-tYcLief** [comment]
Closing as #302 was merged.
