### ISSUE TITLE
Add warning about being careful to not delete tf\custom\tc2 during instalation

### ISSUE THREAD

**Issue by Kenajcrap** [mastercomfig/team-comtress-2#296]
### Description

There were at least 2 players that I know of this week that had problems with the basic installation because they tried to launch TC2 while keeping their customization in `tf\custom\` then when that didn't work, deleted the whole `custom` folder without noticing that pasting` game_clean.zip` had put a new folder there. 
While the installation instructions are completely correct and very clear, never giving the impression you should do things in the reverse order, there will always be people trying stupid stuff and its important to account for that.

### Checklist

- [x] None of the open *or* closed issues document this idea.

### Alternatives

1. Renaming `tf\custom\tc2` something more noticeable
2. Adding a check for it in start_tf2.bat

**Comment by Yttrium-tYcLief** [comment]
Closing as #302 was merged.
