### ISSUE TITLE
Change icon of hl2.exe

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/team-comtress-2#30]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I look at TC2 executable and it looks like half life

**Describe the solution you'd like**
Change default icon to some variation of mastercomfig logo

**Describe alternatives you've considered**
Change default icon to mastercomfig logo

**Additional context**
I know i can just change in windows, I'm just lazy.

**Comment by wgetJane** [comment]
i made this in ms paint in 12 seconds
![epic logo](https://media.discordapp.net/attachments/743724583697383435/747226593029521548/unknown.png)

**Comment by PoorPocketsMcNewHold** [comment]
I´ve did those two in Inkscape, based on the Papirus Team Fortress 2 icon. Both are under GPL license.
<img src="https://gist.githubusercontent.com/PoorPocketsMcNewHold/4fa0e600a01b7f29d3e5689db929afe5/raw/f53de66a4691c1fb886e0d53a40624f14427279e/Team-Comtress-2.svg"><img src="https://gist.githubusercontent.com/PoorPocketsMcNewHold/4fa0e600a01b7f29d3e5689db929afe5/raw/f53de66a4691c1fb886e0d53a40624f14427279e/Team-Comtress-2AlternateWhite.svg">

**Comment by KKire** [comment]
I suggest changing hl2.exe name to tf2.exe too and make it so it does not need launch parameters like `-game tf`

**Comment by micwoj92** [comment]
> I suggest changing hl2.exe name to tf2.exe too and make it so it does not need launch parameters like `-game tf`

@KKire please create separate issue instead of hijacking this one

**Comment by maximsmol** [comment]
> I suggest changing hl2.exe name to tf2.exe too and make it so it does not need launch parameters like `-game tf`

This is actually a bad idea because graphics drivers look for specific .exe names to apply optimizations. Valve did this for CS:GO or something and had to revert for a while I think

**Comment by micwoj92** [comment]
> > I suggest changing hl2.exe name to tf2.exe too and make it so it does not need launch parameters like `-game tf`
> 
> This is actually a bad idea because graphics drivers look for specific .exe names to apply optimizations. Valve did this for CS:GO or something and had to revert for a while I think

This was already closed (as wontfix I think) in other issue. with same explanation/

**Comment by Yttrium-tYcLief** [comment]
We aren't going to be changing the executable icon, but I heavily appreciate the SVG logo, and I'm sure we'll find a use for it.
