### ISSUE TITLE
Overly Shiny Ham Shank

### ISSUE THREAD

**Issue by InfernoSuperNova** [mastercomfig/team-comtress-2#305]
### Description

the porkrind on the ham shank is polished-aluminium shiny
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [idk ngl] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [huds and killsounds only] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. buy ham shank
2. equip hand shank
3. ???
4. profit

### Screenshots

https://drive.google.com/file/d/1xT_1jFyEsE3XVsTJtYb7NqLFZohBN5oN/view?usp=sharing

### Setup Details
- *Server or client:* client
- *Operating system:* windows 10 enterprise
- *Team Comtress version:* 0.0.17
- *Custom content:* tf2hudplus, premium upgrade hud for machine attacks, optivex sounds, consistent kill icons
- *Launch options:* 

- *Graphics driver:* radeon adrenalin 20.8.3
- *DirectX level:* 100

### Performance Details

- *GPU model:* 
- *CPU model:* 
- *RAM amount:* 
- *TF2 installed on:* 
- *TC2 installed on:* 
- *TC2 installation method:*

**Comment by Yttrium-tYcLief** [comment]
Are you using a graphics config?

**Comment by InfernoSuperNova** [comment]
nope

**Comment by Yttrium-tYcLief** [comment]
Does this bug occur if you start the game with the `-default` launch option?

**Comment by InfernoSuperNova** [comment]
i'm not using any launch options, just the batch file

**Comment by Yttrium-tYcLief** [comment]
I'm asking you to try using `-default` to see if it fixes it.

**Comment by InfernoSuperNova** [comment]
ah, okay. i'll give it a go

**Comment by InfernoSuperNova** [comment]
might I ask how I do that?

**Comment by treacherousfiend** [comment]
its a launch option that just makes TF2 remove the current config file and make a new default one

**Comment by Yttrium-tYcLief** [comment]
> its a launch option that just makes TF2 remove the current config file and make a new default one

Not entirely accurate. It basically ignores your config for that session. It won't overwrite anything in it, but it also won't read anything from it.

It's a way to ensure that if you have lingering config data, like from a graphics config you used on live TF2 that got copied from Steam Cloud Sync, it's completely ignored.

**Comment by InfernoSuperNova** [comment]
it appears to fix it, I think

**Comment by Yttrium-tYcLief** [comment]
You likely have leftover config data. Try re-reading the installation instructions in the readme; we updated it today with better instructions regarding Steam Cloud.
