### ISSUE TITLE
Problem with recording button

### ISSUE THREAD

**Issue by daze725** [mastercomfig/team-comtress-2#315]
When you press the record button on the keyboard it will always say that "This server does not support replay."

- [ ] None of the open *or* closed issues document this problem.
- [ ] This is a bug, not a new idea.
- [ yes] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ yes] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [ yes] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

1. All you have to do is press the button on your keyboard that is binded to record (not record demo)

**Comment by mastercoms** [comment]
The server needs to support replay for this to occur. Replay works fine if the server enables it.

**Comment by treacherousfiend** [comment]
To my knowledge, this is not a bug. Replay has been disabled in casual since Meet your Match.
Also, this is something that valve would need to enable themselves.
