### ISSUE TITLE
Document changed console variable default values

### ISSUE THREAD

**Issue by Margen67** [mastercomfig/team-comtress-2#316]
### Description
There's a list of new console variables/commands, but not changed defaults like `snd_mix_async`.

### Checklist
- [x] None of the open *or* closed issues document this idea.

**Comment by treacherousfiend** [comment]
I'll look into it

**Comment by treacherousfiend** [comment]
Created a (hopefully good) wiki page for this, nothing links to it right now, and probably will be edited or merged with the "New cvars and launch options" page, but if you want to check it out here it is.
https://github.com/mastercomfig/team-comtress-2/wiki/Edited-and-removed-console-commands

**Comment by maximsmol** [comment]
Closing as this has been done
