### ISSUE TITLE
Add support for newest huds

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/team-comtress-2#32]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to use up to date team fortress 2 hud with TC2 but it does not work!

**Describe the solution you'd like**
Add support for ui_version 3

**Describe alternatives you've considered**
none

**Additional context**
Things to add:
VCD stuff to change poses on loadout screen. Before JI you could use 
```
"animation"
			{
				"name"		"PRIMARY"
				"activity"	"ACT_MP_STAND_PRIMARY"
				"default"	"1"
```

to use poses in loadout screen, now you need to use VCD

**Comment by Yttrium-tYcLief** [comment]
There is nothing that can really be done about this. TF2 received a fundamental HUD overhaul between the date of this leaked build and the date of Jungle Inferno. We simply don't have the source for that.

**Comment by micwoj92** [comment]
>  We simply don't have the source for that.


Reverse engineering.
