### ISSUE TITLE
Have each class say a "thanks for the teleporter" line every time they go through a teleporter

### ISSUE THREAD

**Issue by NotSoCommonSense** [mastercomfig/team-comtress-2#320]
### Checklist

- [ ] None of the open *or* closed issues document this idea. Yes
- [ ] This is a new idea, not a bug. Yes
- [ ] This idea does not seriously affect game balance. Yes
- [ ] This idea is for the code of the game, not for textures, sounds, or other resources. No
- [ ] This is not an idea for new game content (e.g. new weapons, maps, sounds). Yes
- [ ] This is obviously an improvement, not something that people commonly disagree on. Yes

- [ ] This idea has been implemented in vanilla TF2. No
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league). No
- [ ] This idea has been implemented in a mod.  No
- [ ] This feature has existed in the vanilla game but was removed. No
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems). No

### Screenshots
 N/A

### Alternatives

1. Not sure :/

**Comment by NotSoCommonSense** [comment]
Wait, there are checkboxes? :/

**Comment by treacherousfiend** [comment]
You can edit the issue, also, they already do this

**Comment by NotSoCommonSense** [comment]
> You can edit the issue, also, they already do this



Well it doesn't trigger a line every time you go through a teleporter, only a certain chance
