### ISSUE TITLE
Unreasonable losses

### ISSUE THREAD

**Issue by h9lk** [mastercomfig/team-comtress-2#325]
### Description
Tell you about group of problems
1. Long-standing problems with `.mdl` file loss
2. Lag compensation for no apparent reason and with good connection
3. Game crash when connected to server
Would be very happy if someone can help me figure it out.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

[tf2 dmp.zip](https://github.com/mastercomfig/team-comtress-2/files/5281573/tf2.dmp.zip)

### Screenshots

![20200925112637_1](https://user-images.githubusercontent.com/32390006/94245554-133e2700-ff23-11ea-98ec-ebe69e912772.jpg)

### Setup Details
- *Server or client:* client
- *Operating system:* Windows x64 8.1 pro
- *Team Comtress version:*  ~
- *Custom content:* nohats-bgum, flawhud, no explosion smoke script, surface properties, comanglia's toaster config

- *Launch options:*  -w 1024 -h 768 -novid -high
- *Graphics driver:* 452.06
- *DirectX level:* 8.1

### Performance Details
- *GPU model:* gtx 740
- *CPU model:* AMD Athlon II X2 270
- *RAM amount:* 8GB
- *TF2 installed on:* HDD

### Cfg

[cfg.zip](https://github.com/mastercomfig/team-comtress-2/files/5281638/cfg.zip)

**Comment by wgetJane** [comment]
make an issue for each of these (instead of 3 in 1) and elaborate on each of them

this is also not really a description at all because it's just a list that does not describe anything and is actually just confusing

**Comment by h9lk** [comment]
As for me, too much has been written about first problem loss of files on directx 8.1 in tf2 as familiar and daily as a client crash, file dumps provided. The only thing that is difficult to understand is with lag compensation. I'm confused that nobody is talking about directx 8 problems - apparently no one is going to fix it

**Comment by wgetJane** [comment]
directx 8 is no longer supported in comtress:

> * DirectX 9 is now required to run the game, with DirectX 8 being removed even more, and performance options from DirectX 8 being added to DirectX 9:
>  * Added `tf_disable_weapon_skins 1` to disable weapon skins on DirectX 9
>  * Work is ongoing to add an option to enable low-end shaders traditionally only for DX8, but more investigation needs to be done for which shader fallbacks improve performance and which are only there for the less advanced support DX8 has for shaders.
>  * More info: DirectX 8 is itself a very outdated graphics API. It doesn't inherently improve performance, especially on any card made past 2002. DirectX 9 is a more efficient renderer in many ways: it has support for up to shader model 3, efficient resource management through D3D9Ex, stream offset support for meshes, hardware skinning, vertex textures, increased texture samplers, vertex compression, boolean and integer shader constants, enhanced texture format support, fetch 4 support, and more!
>  * Team Comtress 2 already provides the following DX8 performance options within DX9 mode: `tf_skip_halloween_bomb_hat_translucency`, `r_skybox_lowend`, `-particle_fallback`

create a new issue about the lag compensation problem where you can elaborate on it and provide instructions to reproduce the problem

**Comment by h9lk** [comment]
> 
> 
> directx 8 is no longer supported in comtress:
> 
> > * DirectX 9 is now required to run the game, with DirectX 8 being removed even more, and performance options from DirectX 8 being added to DirectX 9:
> > * Added `tf_disable_weapon_skins 1` to disable weapon skins on DirectX 9
> > * Work is ongoing to add an option to enable low-end shaders traditionally only for DX8, but more investigation needs to be done for which shader fallbacks improve performance and which are only there for the less advanced support DX8 has for shaders.
> > * More info: DirectX 8 is itself a very outdated graphics API. It doesn't inherently improve performance, especially on any card made past 2002. DirectX 9 is a more efficient renderer in many ways: it has support for up to shader model 3, efficient resource management through D3D9Ex, stream offset support for meshes, hardware skinning, vertex textures, increased texture samplers, vertex compression, boolean and integer shader constants, enhanced texture format support, fetch 4 support, and more!
> > * Team Comtress 2 already provides the following DX8 performance options within DX9 mode: `tf_skip_halloween_bomb_hat_translucency`, `r_skybox_lowend`, `-particle_fallback`
> 
> create a new issue about the lag compensation problem where you can elaborate on it and provide instructions to reproduce the problem

Thank you for the answer, it was interesting to read what corrections made and what you plan to do, unfortunately didn't know all details of project, so apologize for such not informative and not competent design of problems. Have lot of problems with reproducing problems, sometimes can understand how they arise from my side, but just cannэt think of how anybody can also reproduce problem. Sorry
