### ISSUE TITLE
1. A feature that allows you to disable hats and other cosmetic particles 2. Medals having their own slots

### ISSUE THREAD

**Issue by BensonMaDude** [mastercomfig/team-comtress-2#326]
### Description
1. Have the option to disable seeing hats based on what slot they are on. There are currently 3 slots for cosmetics. Lets say I want to keep on one hat. I just turn off #2, #3 slots and leave #1 on. 
Second option would be disabling weapon skins, hat paints and particle effects from unusuals, killstreak and cosmetics (Eks: Shellmet's and Soldier's Stogie's smoke effect). It would be nice to reduce smoke from soldiers rockets.

2. Medals feels rather more and more insignificant and yet new competitive ones are added nearly every second month. A slot 3 slot similar for cosmetics dedicated for medals would really be great. Also there should be an option to disable them too.

All this could be placed in to advanced options.
This is inspired by Funke's youtube video: "What Team Fortress 2 NEEDS"

### Checklist

- [ ] None of the open *or* closed issues document this idea.
- [ ] This is a new idea, not a bug.
- [yes ] This idea does not seriously affect game balance.
- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This is not an idea for new game content (e.g. new weapons, maps, sounds).
- [yes ] This is obviously an improvement, not something that people commonly disagree on.

- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ yes] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives

1.

**Comment by Yttrium-tYcLief** [comment]
First off, please only file one feature request/bug per issue report.

> Have the option to disable seeing hats based on what slot they are on. There are currently 3 slots for cosmetics. Lets say I want to keep on one hat. I just turn off #2, #3 slots and leave #1 on.

As far as I'm aware, slot information is not actually provided to the client, but is also irrelevant as you can equip any cosmetic in any slot. Do you really just want to hide items based on their *equip* slot, I.E. what region they actually attach to (permit hats, but not pants, etc)?

> Second option would be disabling weapon skins

This is already implemented in TC2.

> hat paints and particle effects from unusuals, killstreak and cosmetics (Eks: Shellmet's and Soldier's Stogie's smoke effect)

This would likely not happen for consistency reasons. It's important to make all clients render the same thing, within reason.

> It would be nice to reduce smoke from soldiers rockets.

This is literally a balance concern and is out-of-scope.

> Medals feels rather more and more insignificant and yet new competitive ones are added nearly every second month. A slot 3 slot similar for cosmetics dedicated for medals would really be great. Also there should be an option to disable them too.

This is an item schema issue, not just a game client one, and it also requires major UI work, so is therefore out-of-scope.

It's important to remember that **Team Comtress 2 is not a new vision for the game going forward** - it is *literally* only focused on bugfixing and performance, with minor QoL additions that are not controversial.

**Comment by BensonMaDude** [comment]
> First off, please only file one feature request/bug per issue report.
> 
> > Have the option to disable seeing hats based on what slot they are on. There are currently 3 slots for cosmetics. Lets say I want to keep on one hat. I just turn off #2, #3 slots and leave #1 on.
> 
> As far as I'm aware, slot information is not actually provided to the client, but is also irrelevant as you can equip any cosmetic in any slot. Do you really just want to hide items based on their _equip_ slot, I.E. what region they actually attach to (permit hats, but not pants, etc)?
> 
> > Second option would be disabling weapon skins
> 
> This is already implemented in TC2.
> 
> > hat paints and particle effects from unusuals, killstreak and cosmetics (Eks: Shellmet's and Soldier's Stogie's smoke effect)
> 
> This would likely not happen for consistency reasons. It's important to make all clients render the same thing, within reason.
> 
> > It would be nice to reduce smoke from soldiers rockets.
> 
> This is literally a balance concern and is out-of-scope.
> 
> > Medals feels rather more and more insignificant and yet new competitive ones are added nearly every second month. A slot 3 slot similar for cosmetics dedicated for medals would really be great. Also there should be an option to disable them too.
> 
> This is an item schema issue, not just a game client one, and it also requires major UI work, so is therefore out-of-scope.
> 
> It's important to remember that **Team Comtress 2 is not a new vision for the game going forward** - it is _literally_ only focused on bugfixing and performance, with minor QoL additions that are not controversial. We do not touch game assets and have no access to the item schema, we _only_ touch code.


By hats I also mean cosmetics of all kind. I understand now what can't be changed. Thanks for the reply and keep doing the good work. 👍
