### ISSUE TITLE
Mat_phong 0 

### ISSUE THREAD

**Issue by PaPaSoulzune** [mastercomfig/team-comtress-2#329]
Mat_phong 0 broke a lot of MVM textures and I'd really love to finally see them fixed in normal casual servers. I don't really know a lot about TF2 code so sorry if there isn't a huge notepad file here. I'd really love to finally get this fixed tho.

![23413223112332121232132312321323123123123](https://user-images.githubusercontent.com/16678101/94306760-88b8f000-ff41-11ea-9f7e-de6d28ce3036.png)

Also posted a link to a mod that fixes it (only in servers that allow it) to see if this will help in any way.
https://gamebanana.com/skins/138140

**Comment by Yttrium-tYcLief** [comment]
This is an asset problem and not a game code problem, so is out-of-scope, unfortunately. However, you did report it at agrastiOs/Ultimate-TF2-Visual-Fix-Pack#17 , which is the proper place for this kind of report.
