### ISSUE TITLE
MVM Upgrade Shop UI closes when any chat alert happens

### ISSUE THREAD

**Issue by treacherousfiend** [mastercomfig/team-comtress-2#342]
### Description
Whenever a chat alert happens (Players joining/leaving, Chat messages. or even Item/Achievement getting), any players in the MVM Upgrade Shop will get kicked out and any purchases that weren't finalized are canceled.

Edit: I've been informed that Strange items ranking up (the chat alert that it gives off) also triggers this bug. This includes some of the other "strange" items like soul gargoyles.
(Thanks for the info Beletrix935!)

This bug is also documented on the TF2 Wiki: https://wiki.teamfortress.com/wiki/Upgrade_Station#Bugs

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch. (Untested, but this bug has been happening for years, so its likely on TC2 as well)
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Open MVM server (map does not matter)
2. Have Player 1 go into Upgrade Shop
3. Force chat alert (have another player join, etc.)

### Setup Details
- *Server or client:* Client 
- *Operating system:* Windows 10 
- *Team Comtress version:* N/A 
- *Custom content:* Mastercomfig (Latest) High Preset, Disable Pyroland Addon, No Tutorial Addon, Missing Killicons (adds killicons to things that do not have them), TF2 Ultimate Visual Fix, Class configs for every class, Autoexec, Game_overrides 
- *Launch options:* -novid -nojoy -nosteamcontroller -nohltv -particles 1 

- *Graphics driver:* 452.06 Studio Driver 
- *DirectX level:* 100 

### Performance Details

- *GPU model:* NVIDIA GTX 1070 
- *CPU model:* INTEL I7-7700K
- *RAM amount:* 16GB 
- *TF2 installed on:* HDD 
- *TC2 installed on:* 
- *TC2 installation method:*

**Comment by int-72h** [comment]
This has happened at least since Tough Break when I started to play.
I'd be glad to see it die, one could go about this by seeing how the chat overrides the menu ui (maybe by setting a breakpoint for when the menu closes and looking at the backtrace)

**Comment by treacherousfiend** [comment]
Hopefully fixed by PR #472 
still needs some testing, but from my testing it seems to work flawlessly

**Comment by melvyn2** [comment]
> Hopefully fixed by PR #472
> still needs some testing, but from my testing it seems to work flawlessly

Probably shouldn't be closed until the PR is merged, no?

**Comment by treacherousfiend** [comment]
doesn't really matter, I can reopen it if necessary
