### ISSUE TITLE
Gloves of running urgently removes overheal

### ISSUE THREAD

**Issue by treacherousfiend** [mastercomfig/team-comtress-2#343]
### Description
Gloves of running urgently slowly reduces the max health of the player while it is out, which in turn will cause max overheal to decrease as well, THIS IS INTENTIONAL.
However, if the player has the gloves of running urgently out and puts them away _while still having overheal_ that is above 300 health, the overheal is completely removed and the player is taken back to 300 health. THIS IS MOST LIKELY NOT INTENTIONAL.

This could potentially also be used for uber farming, as a heavy, one of the easiest classes to farm uber with, can remove all overheal at will.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [ ] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch. **Unfortunately I cannot test this, as my TC2 install is being finicky, however the current GRU was added in JI and most likely is present here**
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Have player 1 play as heavy with the gloves of running urgently equipped (BUT NOT ACTIVE)
2. Have player 2 play as medic and overheal the heavy
3. Have player 1 switch to GRU and then off of it while still above 300HP

### Setup Details
- *Server or client:* Client 
- *Operating system:* Windows 10 
- *Team Comtress version:* N/A 
- *Custom content:* Mastercomfig (Latest) High Preset, Disable Pyroland Addon, No Tutorial Addon, Missing Killicons (adds killicons to things that do not have them), TF2 Ultimate Visual Fix, Class configs for every class, Autoexec, Game_overrides 
- *Launch options:* -novid -nojoy -nosteamcontroller -nohltv -particles 1 

- *Graphics driver:* 452.06 Studio Driver 
- *DirectX level:* 100 

### Performance Details

- *GPU model:* NVIDIA GTX 1070 
- *CPU model:* INTEL I7-7700K
- *RAM amount:* 16GB 
- *TF2 installed on:* HDD 
- *TC2 installed on:* 
- *TC2 installation method:*

**Comment by Yttrium-tYcLief** [comment]
> however the current GRU was added in JI and most likely is present here

Balance changes added in JI do *not* exist in TC2. They were implemented later in development. If this bug cannot be reproduced in TC2 it's pretty much impossible for us to reproduce it.
