### ISSUE TITLE
Contributor License Agreement

### ISSUE THREAD

**Issue by mastercoms** [mastercomfig/team-comtress-2#352]
For those who have contributed to Team Comtress 2 before the establishment of CLA assistant, you will need to [sign the Contributor License Agreement](https://cla-assistant.io/mastercomfig/team-comtress-2) with your GitHub account here, or your contributions will be removed from the project.

cc: @maximsmol @micwoj92 @wgetJane @Margen67 @Yttrium-tYcLief @Thestickman391 @pete-tf @melvyn2 @treacherousfiend @infirms @devvoid @agrastiOs @Zionner @Kenajcrap @FlaminSarge @zooxy

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/94372238-45ef4780-00fc-11eb-898f-2ac73fde2764.png)

**Comment by Margen67** [comment]
Signed.

**Comment by mastercoms** [comment]
Everyone but @devvoid has signed. I'll have the issue become a week old before removing.

**Comment by mastercoms** [comment]
As stated, will be removing @devvoid's contributions today.
