### ISSUE TITLE
Flamethrower airblast and flames happen at the same time 

### ISSUE THREAD

**Issue by maxwellhupig** [mastercomfig/team-comtress-2#359]
### Description
 Sometimes a pyro will both airblast and shoot out flames infinitely. 

### Checklist

- [ yes] None of the open *or* closed issues document this problem.
- [ yes] This is a bug, not a new idea.
- [ yes] This is objectively a bug, and not something that people commonly disagree on.
- [ yes] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ yes] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [ ] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Shounic explained how the glitch works here https://www.youtube.com/watch?v=yDShQA-GLro&ab_channel=shounic

### Screenshots

![image](https://user-images.githubusercontent.com/71421111/94373206-a8beef80-00b8-11eb-8e57-f06bb0187dde.png)

### Setup Details
- *Server or client:* 
- *Operating system:* 
- *Team Comtress version:* 
- *Custom content:* 
- *Launch options:* 

- *Graphics driver:* 
- *DirectX level:* 

### Performance Details

- *GPU model:* 
- *CPU model:* 
- *RAM amount:* 
- *TF2 installed on:* 
- *TC2 installed on:* 
- *TC2 installation method:*

**Comment by Yttrium-tYcLief** [comment]
Does this actually occur in TC2? I feel like we've fixed this. Will triage further later.

**Comment by mastercoms** [comment]
It was fixed almost a decade ago, and then was broken again in Jungle Inferno. We can't fix it.
