### ISSUE TITLE
Eyelander heads and Vita-Saw organs share the same counter

### ISSUE THREAD

**Issue by renimg** [mastercomfig/team-comtress-2#369]
### Description
If the medic has the vita saw, and a demoman kills him with the eyelander, however many organs the medic had will be directly transferred over to heads

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).

### Reproduction
1. Select Medic with the Vita-Saw equipped
2. Gather organs
3. Have a demoman with the Eyelander kill him

### Screenshots
video demonstration
http://totally-not.a-sketchy.site/92q4SoQ.mp4

**Comment by mastercoms** [comment]
I think kill counter stats like that are intended.

**Comment by Margen67** [comment]
> 
> 
> I think kill counter stats like that are intended.

The code might be checking if the victim is a demo, so it might not be intended:
https://github.com/mastercomfig/team-comtress-2/blob/master/game/shared/tf/tf_weapon_sword.cpp#L338-L340

**Comment by mastercoms** [comment]
That's not the victim, that's the person swinging the sword. It's saying that only demos have the kill counter collection ability with swords.
