### ISSUE TITLE
Lower the min limit on ds_min_streak to 1 so  all my kills can be logged 

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/team-comtress-2#37]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I only get one kill but it is not logged.

**Describe the solution you'd like**
Lower the min limit on ds_min_streak

**Describe alternatives you've considered**
none

**Additional context**
high priority, bad player

**Comment by wgetJane** [comment]
> **Describe alternatives you've considered**
> none

alternative: stop feeding

**Comment by micwoj92** [comment]
but when i play spy i just go for 1 med pick and dont care if i die after 1 kill

**Comment by wgetJane** [comment]
if it's not a chainstab then it doesn't deserve to be recorded
