### ISSUE TITLE
(Windows 10) start_tf2.bat does not launch Team Comtress 2 after following all installation instructions

### ISSUE THREAD

**Issue by Susorodni** [mastercomfig/team-comtress-2#373]
Hello,

I installed the latest version of Team Comtress 2 and followed all of the instructions. 
When I tried to launch it via start_tf2.bat, the game does not launch.
I tried running it in the command prompt, but got no errors.
I do not exactly know why this is happening, did anyone have a similar situation?

**Comment by micwoj92** [comment]
Show folder with path, screenshot

**Comment by treacherousfiend** [comment]
this is already fixed, reinstall

**Comment by Susorodni** [comment]
> this is already fixed, reinstall

I just installed 0.1.2, I think I got the "fix"

**Comment by treacherousfiend** [comment]
the fix was literally a rerelease of 1.2

**Comment by micwoj92** [comment]
It should be called 0.1.2.1 then

**Comment by Susorodni** [comment]
I literally downloaded it minutes ago, are you sure it changed in that time?

**Comment by treacherousfiend** [comment]
Yes, i'm in the discord
