### ISSUE TITLE
Minigun spread is currently bugged and inconsistent

### ISSUE THREAD

**Issue by LordExor** [mastercomfig/team-comtress-2#376]
The spread on all miniguns is currently glitched, debilitating Heavy's effective DPS. The miniguns will periodically miss targets, causing delays between hits. 

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. This issue can be easily replicated by comparing results between live TF2 and Comtress; I recommend itemtest or a training map such as tr_newbots. Rev and fire. 

### Screenshots
Live TF2: https://streamable.com/xx89xb
Comtress: https://streamable.com/1x1mva

### Setup Details
- *Server or client:*  Both
- *Operating system:*  Windows 10
- *Team Comtress version:*  0.1.2
- *Custom content:*  No.
- *Launch options:* 
- *Graphics driver:* 
- *DirectX level:*  Direct X Level 100

### Performance Details

- *GPU model:* NVIDIA 2080ti
- *CPU model:* Intel i9-9900k
- *RAM amount:* 16GB
- *TF2 installed on:* SSD
- *TC2 installed on:* SSD
- *TC2 installation method:* Basic

**Comment by Yttrium-tYcLief** [comment]
Since this seems to be a TC2-specific issue, can you find an earlier version of TC2 that doesn't have this issue? Will help with regression testing.

**Comment by LordExor** [comment]
It worked as of 0.0.11.
