### ISSUE TITLE
Itemtest sentries only attack blu players

### ISSUE THREAD

**Issue by rcmaehl** [mastercomfig/team-comtress-2#377]
### Description
No matter what team a sentry is on in itemtest, it will always attack Blu players and never Red players. Red bots will attack Blu sentries however.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. Run `map itemtest`
2. Run `sv_cheats 1`
3. Run `tf_bot_quota 2`
4. Run `ent_create obj_sentrygun teamnum 1 defaultupgrade 3 spawnflags 10`
5. Run `ent_create obj_sentrygun teamnum 2 defaultupgrade 3 spawnflags 10` 

### Screenshots
![image](https://user-images.githubusercontent.com/716581/94639409-1e3de200-02aa-11eb-9cc0-6741cdc62a41.png)

### Setup Details
- *Server or client:* Client
- *Operating system:* Windows 10
- *Team Comtress version:* 0.1.3
- *Custom content:* N/A
- *Launch options:* N/A

- *Graphics driver:* N/A
- *DirectX level:* N/A

### Performance Details

- *GPU model:* N/A
- *CPU model:* N/A
- *RAM amount:* N/A
- *TF2 installed on:* N/A
- *TC2 installed on:* N/A
- *TC2 installation method:* N/A

**Comment by mastercoms** [comment]
Spectator team is 1. Blu is 2. Red is 3.

**Comment by rcmaehl** [comment]
So teams are not 0 based? Why the hell does teamnum 0 work then. Damn it valve

**Comment by mastercoms** [comment]
0 is unassigned.
