### ISSUE TITLE
Visual bug with the bullets fired from a Lvl 2 and 3 Sentry Gun

### ISSUE THREAD

**Issue by TheShpeeCrab** [mastercomfig/team-comtress-2#379]
In vanilla TF2, there is a visual bug with the bullets being fired from a lvl 2 and 3 Sentry Gun. When a lvl 2 or 3 sentry gun is firing, the bullets only appear to be fired out of the left gatling gun.

**Comment by Yttrium-tYcLief** [comment]
Please use the proper bug report template next time.

![image](https://user-images.githubusercontent.com/1037011/94656310-eba5e080-02cd-11eb-977e-316d6516c602.png)

**Comment by Yttrium-tYcLief** [comment]
Closing in favor of #384
