### ISSUE TITLE
Visual bug with the bullets fired from a Lvl 2 and 3 Sentry Gun 

### ISSUE THREAD

**Issue by TheShpeeCrab** [mastercomfig/team-comtress-2#384]
### Description
 In vanilla TF2, there is a visual bug with the bullets being fired from a lvl 2 and 3 Sentry Gun. While the lvl 2 or 3 sentry gun is firing, the bullets only appear to be coming out of the left gatling gun instead of both of them. Also I cannot get a screenshot since the bullets are too fast to be captured. I have even seen this bug occur on other peoples' systems, even on the TF2 Wiki YouTube video on the Sentry Gun.

### Checklist

- [ ] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [ ] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1.

### Setup Details
- *Server or client:* 
- *Operating system:* <Windows 10 64-bit>
- *Team Comtress version:* 
- *Custom content:* 
- *Launch options:* 

- *Graphics driver:* 
- *DirectX level:* 

### Performance Details

- *GPU model:* <AMD Radeon R7 240>
- *CPU model:* <AMD FX(tm)-6300 Six-Core Processor>
- *RAM amount:* <8 GB>
- *TF2 installed on:* HDD
- *TC2 installed on:* 
- *TC2 installation method:*

**Comment by Yttrium-tYcLief** [comment]
Does this happen in TC2 as well?

Please edit your report to populate your hardware/setting details.

**Comment by mastercoms** [comment]
I don't see this bug happen in TC2.
