### ISSUE TITLE
Allow killstreak attribute to work on the gas passer

### ISSUE THREAD

**Issue by CoolJosh3k** [mastercomfig/team-comtress-2#386]
### Description

If a gas passer is made to have killstreaks (via attribute 2025 "killstreak tier"), it stops working.
The pyro can hold it, but there is no charge meter and it cannot be charged anyway.

### Solution

Allow the gas passer to function if it has the killstreak attribute.
This would allow usage of the gas passer to still give killstreak credits for kills, should the TF2 team add a basic gas passer killstreak kit to the game after being fixed.

### Alternatives

Allow a killstreak primary weapon to gain credit for kills made using the gas passer.
This is, for example, how the wrangler works. (I observed via testing).

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [x] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using a dedicated server.

### Reproduction

1a. Use the TF2Items or TF2Attributes extension/plugin for sourcemod.
1b. Force all gas passer items to be a tier 1 killstreak (basic) via the 2025 attribute.
1c. Attempt to use it.

2a. Use a "glitched" killstreak kit on a gas passer.
2b. Attempt to use it.

### Screenshots

![TF2_KillstreakKit_Basic_GasPasser](https://user-images.githubusercontent.com/71309141/94805293-81a54c80-042f-11eb-9651-241c9acf31ff.png)

**Comment by micwoj92** [comment]
Gaspasser doesnt exist.

**Comment by CoolJosh3k** [comment]
Oh, you mean it as created after the date of this source? Well then, I dun goofed.

**Comment by micwoj92** [comment]
Have you ever played TC2?

**Comment by Yttrium-tYcLief** [comment]
Closing since GP doesn't exist in our current build.
