### ISSUE TITLE
Move game_clean

### ISSUE THREAD

**Issue by Margen67** [mastercomfig/team-comtress-2#406]
### Description
With assets (models, materials, etc) potentially being merged, game_clean should be moved to either another repository, or a different branch before it becomes too bloated and makes cloning the repository take an absurd amount of time.

### Checklist
- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [x] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod.
- [ ] This feature has existed in the vanilla game but was removed.
- [x] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

**Comment by micwoj92** [comment]
I heard that mastercoms will add submodule.

**Comment by mastercoms** [comment]
Just asking, is your goal to make the assets optional?

**Comment by Margen67** [comment]
> 
> 
> Just asking, is your goal to make the assets optional?

It's to have separate repos for code and binaries so the main repo doesn't get bloated, and then ends up taking a long time to clone.

Making the assets optional by making them a submodule like micwoj92 mentioned is a good way of doing this.

**Comment by mastercoms** [comment]
Please answer the question directly. If assets are not optional, there is no "bloat".

**Comment by Margen67** [comment]
> 
> 
> Please answer the question directly. If assets are not optional, there is no "bloat".

Yes.

**Comment by Margen67** [comment]
https://github.com/mastercomfig/team-comtress-2/commit/6f496e814b3887f7ecd70821c2d6d98413a5b5b9
https://github.com/mastercomfig/team-comtress-2/commit/c837656fcdd5bafe98457f23a80c7b8a6ef4763a
