### ISSUE TITLE
Opt-in to Hacktoberfest for the repo

### ISSUE THREAD

**Issue by FlaminSarge** [mastercomfig/team-comtress-2#409]
### Description

Unless you see any concerns with this, I figure might as well make this repo Hacktoberfest-eligible since they changed to an opt-in model this year: https://hacktoberfest.digitalocean.com/details#details
Requires adding a 'hacktoberfest' topic to the repo on GitHub, that should be all that's necessary for this.

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This issue is regarding documentation (I.E. something on GitHub), and not the game client itself.

### Alternatives

1. 
2. 
3.

**Comment by mastercoms** [comment]
Done!
