### ISSUE TITLE
koth_slasher truce freezes time while the control point belongs to a team

### ISSUE THREAD

**Issue by vlad55523** [mastercomfig/team-comtress-2#416]
### Checklist

- [x ] None of the open *or* closed issues document this problem.
- [ x] This is a bug, not a new idea.
- [ x] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [ x] This issue occurs on the latest vanilla TF2 update.

- [x ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [ x] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x ] This issue occurs when using a listen server (using the `map` command ingame).
- [ x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
 just spawn merasmus using cheats while you control the point, can easily be fixed if point would become neutral

1.
2.
3.

#### Client Settings

- *Server or client:* 
- *Operating system:* 
- *Team Comtress version:* 
- *Custom content:* 
- *Launch options:* 
#### Driver Version

- *Graphics driver:* 
- *DirectX level:* 
#### Hardware Specs

- *CPU model:* 
- *GPU model:* 
- *RAM amount:* 
- *TF2 install location:* 
- *TC2 install location:* 
- *TC2 installation method:*

**Comment by agrastiOs** [comment]
Sounds too subjective to be worthy of a fix.

**Comment by treacherousfiend** [comment]
This honestly sounds intentional, since having the point while you can't kill enemies is basically an easy win

**Comment by Yttrium-tYcLief** [comment]
This is definitely intentional behavior, but is also part of the map itself, so it's out of scope for TC2.
