### ISSUE TITLE
Make killstreak into its own quality

### ISSUE THREAD

**Issue by henriquecm** [mastercomfig/team-comtress-2#428]
### Description
Make it so that killstreak weapons are considerate to be a new quality of item, just like strange or unusual.

This would make easier to filter items on steam inventory, and would remove killstreak items from craft screen when the option to hide special qualities is checked.

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Screenshots

![image](https://user-images.githubusercontent.com/15136037/95545052-382aa380-09d3-11eb-9399-79c5f68e9649.png)
Random color just make it look different on screenshot, but it's no actually needed

### Alternatives

1. 
2. 
3.

**Comment by micwoj92** [comment]
I really like this idea, but this is out of scope as it would require changes outside of the game :/

**Comment by Yttrium-tYcLief** [comment]
This is definitely outside the scope of this project, and it's also not really feasible - there's a *lot* of issues this would introduce.
