### ISSUE TITLE
[MvM] Missing Upgrade Ranks (Rounding Error)

### ISSUE THREAD

**Issue by Beletrix935** [mastercomfig/team-comtress-2#429]
### Description
When using the upgrade station in MvM with certain weapons that have different base stats, some upgrade ranks will be missing due to the rank value being rounded up or down dynamically whereas it should be consistently rounded up when not a full integer. An example of this would be the Vaccinators Ubercharge Rate stat: it should have 2 "+25% Ubercharge Rate" upgrades to reach the cap of "+100% Ubercharge Rate", however in game it is only given 1 "+25% Ubercharge Rate" upgrade. From my research I have found it is more than likely tied to the game\shared\tf\tf_upgrades_shared.cpp file within the game's code, more specifically at line 281, as shown below:

`nNumSteps = RoundFloatToInt( fabsf( ( flCap - flBase ) / flIncrement ) );`

### Fix
I believe this could easily be fixed by simply forcing the equation to round the resulting value up always instead of rounding it up or down via dynamic rounding as it currently does via "RoundFloatToInt", I have listed a number of adjustments which I have hypothesized to fix the issue below (I am currently unable to test it myself due to being unable to create a working environment):

1. `nNumSteps = ceilf( fabsf( ( flCap - flBase ) / flIncrement ) );`
2. `nNumSteps = ceil( fabsf( ( flCap - flBase ) / flIncrement ) );`
3. `nNumSteps = RoundFloatToInt( 0.5 + ( fabsf( ( flCap - flBase ) / flIncrement ) ) );`

### Reproduction

1. Equip any of the following weapons: Pretty Boy's Pocket Pistol, Wrap Asassin, Scottish Resistance, Scotman's Skullcutter, Family Business, Vaccinator
2. Use the upgrade station
3. Upgrade the respective base state for chosen weapon (EG: +25% Ubercharge Rate on the vaccinator)
4. Said stat cannot reach the cap defined in "Team Fortress 2\tf\tf_misc_dir.vpk\scripts\items\mvm_upgrades.txt" due to not having enough upgrade ranks provided 

### Screenshots
As there are many instances of this bug instead I have linked a guide in which I have explained how to bypass these set limits via another glitch. All instances of these non-obtainable upgrades are shown here (aside from the Soda Popper, Force-a-Nature, Rocket Jumper and Sticky Jumper instances, which are based around a seperate bug tied to "Team Fortress 2\tf\tf_misc_dir.vpk\scripts\items\mvm_upgrades.txt"). My guide is linked below:
https://steamcommunity.com/sharedfiles/filedetails/?id=2114727049

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs on the latest vanilla TF2 update.

- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

#### Client Settings

- *Server or client:* Client 
- *Operating system:* Windows 10
- *Team Comtress version:* Vanilla TF2
- *Custom content:* None
- *Launch options:* None

**Comment by int-72h** [comment]
The specific fixes are greatly appreciated- saves a lot of time. This is a *perfect* issue if I've ever seen one.
I'll test this out if/when I get a relatively stable build on Linux.

**Comment by mkeller3204** [comment]
So this would fix the issue and make it so that weapons can reach the hard cap set by valve in the game without having to ghost upgrade, you run into an issue where the last upgrade is less useful than the rest, meaning it will say “+25% ÜberCharge rate” in the upgrade station, but you only get a +8% bonus while paying for a 25%. Maybe try like 
`nNumSteps = ceilf( fabsf( ( flCap - flBase ) / flIncrement ) )` as a way to get the proper amount of increments then do something like 
`flNewIncrement = ((flCap - flBase)/flincrement)`

I know this is pretty flawed and changes the actual game mechanics but it would make each upgrade more consistent. But in terms of fixing the bug where the increments are wrong and don’t allow you to reach max stats without ghost upgrading, using floor instead of round would fix the issue. I will try to get a working build and test this

**Comment by Beletrix935** [comment]
@mkeller3204 
That is true, but there are already cases of that in the live game. There are a few instances of the an upgrade only giving partial benefit due to the hard cap. A good example of this would be the Quick-Fix, which has 4 "+25% Ubercharge Rate" upgrades, yet the 4th one only gives 15% due to the cap set in mvm_upgrades.txt. 
I am of the opinion that a player should have the choice to reach the cap of an upgradable attribute with any weapon which it is available on through the upgrade station and shouldn't be hindered due to base attributes, a notable example of this hinderance would be the Demomans Stickybomb Launchers, where stock can reach "+40% Firing Speed" but the Scottish Resistance is hindered to "+35% Firing Speed" when using the upgrade station as intended.

**Comment by DrCactusTF2** [comment]
Yeah, the upgrade limiter system is a bit flawed, and doesn't really take other important things into accounts, and just makes already inferior weapon choices (like Direct Hit) even worse.
It also isn't very accurate, since it doesn't account for things like the beggar's bazooka's firing speed, or healing mastery with quick-fix

**Comment by treacherousfiend** [comment]
just tested this (and messaged Beletrix about it), This has a lot of issues right now as the menu kind of breaks after you buy the upgrades. I'll share the example I gave Beletrix.

"for example the vaccinator has +67% uber rate, so one upgrade takes it to +92%, and then the second upgrade takes it to +100%.
Going back into the menu after buying both these reveals that there is now only one upgrade again, the menu says removing it goes down to +75%, but it actually removes both and goes back down to default."

**Comment by Beletrix935** [comment]
@treacherousfiend 
After having another look into the file I found another equation which is tied to showing the clients current upgrade rank, I believe that issue be caused by said equation which I have placed below:
`nCurrentStep = RoundFloatToInt( fabsf( ( flCurrentAttribValue - flBase ) / flIncrement `
It may be worth replacing both instances of said equation with the following:
`nCurrentStep = ceilf( fabsf( ( flCurrentAttribValue - flBase ) / flIncrement ) );`

**Comment by Beletrix935** [comment]
This seems to be fixed through #482 as tested by @treacherousfiend
