### ISSUE TITLE
fps_max 0 causes timescale to change at high fps

### ISSUE THREAD

**Issue by funnything1** [mastercomfig/team-comtress-2#440]
### Description

If you uncap fps with fps_max 0 and create your own server, your game will run faster based on how high your fps is. Setting fps_max 999 this won't happen. This works in vanilla tf2 but is much more noticeable in tc2 because of the performance improvements. 
Probably an engine bug
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs on the latest vanilla TF2 update.

- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Set fps_max to 0 in console
2. Create your own server
3. Get your fps to around 800+ in game to notice the affect (lower settings and play on a simple map)

I was able to get around 2000 fps and it seemed like host_timescale was set to 2
### Video

[https://youtu.be/gFktGGkMzq0](https://youtu.be/gFktGGkMzq0)
#### Client Settings

- *Server or client: Client* 
- *Operating system: Windows 10* 
- *Team Comtress version: 0.1.9* 
- *Custom content:* 
- *Launch options:* 
#### Driver Version

- *Graphics driver: 456.71* 
- *DirectX level: 10* 
#### Hardware Specs

- *CPU model: 7700k* 
- *GPU model: 2080 Super* 
- *RAM amount: 32GB* 
- *TF2 install location: SSD* 
- *TC2 install location: SSD* 
- *TC2 installation method: Basic*

**Comment by mastercoms** [comment]
It's not really possible to do unfortunately, because there would need to be two instances of the game running, one for the server and one for the client, and this would be an extremely difficult task doing this within the same program. Not to mention the side effects to normal operation that would most likely arise. So either use fps_max or a separate dedicated server launch.
