### ISSUE TITLE
Terrible Performance When Running From Master Branch

### ISSUE THREAD

**Issue by higgy999** [mastercomfig/team-comtress-2#441]
### Description

Running the game from release, the performance is incredible. But when running from master the game throws so many assert errors and I get 30 FPS in the menus and 10 in game. Should I be not using master when developing?

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.

- [ ] This issue occurs on the latest vanilla TF2 update.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Follow the development guide
2. Launch the Game

#### Client Settings

- *Server or client:* Client
- *Operating system:* Windows 10 20H2
- *Team Comtress version:* master
- *Custom content:* None
#### Driver Version

- *Graphics driver:* 456.71
- *DirectX level:* 100
#### Hardware Specs

- *CPU model:* Intel i5-4590
- *GPU model:* NVIDIA RTX 2060
- *RAM amount:* 16 GB
- *TF2 install location:* SSD
- *TC2 install location:* SSD
- *TC2 installation method:* Advanced

**Comment by mastercoms** [comment]
Select Release instead of Debug configuration.

**Comment by higgy999** [comment]
> Select Release instead of Debug configuration.

Thank you!
