### ISSUE TITLE
[MvM] Removal of Excess Firing Speed Upgrade

### ISSUE THREAD

**Issue by Beletrix935** [mastercomfig/team-comtress-2#451]
### Description
Within the "game\shared\tf\tf_gamerules.cpp" file inside the games code, there is a section of code which allows for upgrades to have modified prices depending on certain variables. This code can be used to remove an unnecessary upgrade from the "tf\tf_misc_dir.vpk\scripts\items\mvm_upgrades.txt" file. In mvm_upgrades there is a second firing speed upgrade specifically for heavy, with the only difference between the two being the price. To lessen the amount of upgrades in the mvm_upgrades.txt file this instead can be written as a cost modification rule in tf_gamerules.cpp. I have explained how I think this can be done in the fix section.

### Implimentation
Firstly the upgrade "//Fire Speed - Expensive" should be deleted from mvm_upgrades.txt. After this is done a few modifications will need to be made to the tf_gamerules.cpp file. These are as follows:
1. add the following after line 2990
```
            if ( iItemSlot == LOADOUT_POSITION_PRIMARY && nClass == TF_CLASS_HEAVYWEAPONS )
            {
                switch ( pAttr->GetDefinitionIndex() )
                {
                case 6:        // fire rate bonus
                    iCost *= 1.75f;
                    break;
                default:
                    break;	
				}
			}
```
2. change lines 21159 through 21180 (case 6) to the following
```
    case 6:        // "fire rate bonus"
        {
            return ( iWeaponID == TF_WEAPON_GRENADELAUNCHER && pWeapon && pWeapon->AutoFiresFullClipAllAtOnce() );
        }

            // Non-melee version
            return ( dynamic_cast< CTFWeaponBaseMelee* >( pEntity ) == NULL && 
                iWeaponID != TF_WEAPON_NONE && !bHideDmgUpgrades && 
                iWeaponID != TF_WEAPON_FLAMETHROWER && 
                !WeaponID_IsSniperRifleOrBow( iWeaponID ) && 
                !( pWeapon && pWeapon->HasEffectBarRegeneration() ) );
        }
        break;
```
2 (alternative). if the fix I have suggested in issue #450 has been implimented, change lines 21159 through 21180 (case 6) to the following
```
    case 6:        // "fire rate bonus"
        {
            if ( nQuality == MVM_UPGRADE_QUALITY_HIGH )
            {
                return ( iWeaponID == TF_WEAPON_SODA_POPPER || iWeaponID == TF_WEAPON_SCATTERGUN && pWeapon->Scattergun_NoReloadSingle )
            }
            else if ( iWeaponID == TF_WEAPON_GRENADELAUNCHER && pWeapon && pWeapon->AutoFiresFullClipAllAtOnce() )
            {
                return false;
            }

            // Non-melee version
            return ( dynamic_cast< CTFWeaponBaseMelee* >( pEntity ) == NULL && 
                iWeaponID != TF_WEAPON_NONE && !bHideDmgUpgrades && 
                iWeaponID != TF_WEAPON_FLAMETHROWER && 
                !WeaponID_IsSniperRifleOrBow( iWeaponID ) && 
                !( pWeapon && pWeapon->HasEffectBarRegeneration() ) );
        }
        break;
```

### Attachments
I have attached ammended versions of the files relevant to this issue, including both versions of the 2nd modification mentioned above. These files are attached below in the form of a .zip archive:
[[MvM] Removal of Excess Firing Speed Upgrade.zip](https://github.com/mastercomfig/team-comtress-2/files/5372450/MvM.Removal.of.Excess.Firing.Speed.Upgrade.zip)

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

**Comment by mastercoms** [comment]
I think this adds very little value and may break custom scripts/expected behavior.
