### ISSUE TITLE
Sniper:  shooting immediately after scoping in will never count as a headshot for any sniper

### ISSUE THREAD

**Issue by funnything1** [mastercomfig/team-comtress-2#459]
### Description

As a sniper, if you zoom in at an enemy's head and shoot immediately your shot will never count as a headshot. For some reason using crits fixes this.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs on the latest vanilla TF2 update.

- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1.  Zoom in 
2.  Shoot immediately at a head

### Video

[https://youtu.be/YOdK9YvYewE](https://youtu.be/YOdK9YvYewE)

#### Client Settings

- *Server or client: Client* 
- *Operating system: Windows 10* 
- *Team Comtress version: 0.1.10* 
- *Custom content:* 
- *Launch options:* 
#### Driver Version

- *Graphics driver: 456.71* 
- *DirectX level: 10* 
#### Hardware Specs

- *CPU model: 7700k* 
- *GPU model: 2080 Super* 
- *RAM amount: 32GB* 
- *TF2 install location: SSD* 
- *TC2 install location: SSD* 
- *TC2 installation method: Basic*

**Comment by spook953** [comment]
You have to wait 200 milliseconds after scoping in for the shot to count as a headshot, it's not a bug.

**Comment by wgetJane** [comment]
https://wiki.teamfortress.com/wiki/February_14,_2008_Patch

> Added a small delay (200 ms) before a zoomed Sniper shot can get a Critical hit
