### ISSUE TITLE
Lightwarp and thirdperson airblast animations

### ISSUE THREAD

**Issue by condor00fr** [mastercomfig/team-comtress-2#474]
A new, more cartoony Lightwarp would be nice instead of the "realistic" one we currently have.
also
 pyros and pyro bots have an unused thirdperson airblast animation in the files, so why not using it?

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).

**Comment by agrastiOs** [comment]
A lightwarp is way too subjective for a change. 

Pyro bot suggestion  sounds good, but should be opened as a separate issue.
