### ISSUE TITLE
Missing maps from casual

### ISSUE THREAD

**Issue by MikhailaTF** [mastercomfig/team-comtress-2#478]
### Description
 When the current method of finding playing casual TF2 was introduced, Valve forgot to add several maps to the list, most of which have now been rectified.
However, a few are still missing, most notably the entire arena game mode (badlands, byre, granary, lumberyard, nucleus, offblast, ravine, sawmill, watchtower and well) as well as pl_cactuscanyon and rd_astroid
While it could be argued that pl_cactuscanyon and rd_astroid were never really finished, I don't see much reason why arena is no longer part of the casual options.

### Checklist

- [X] None of the open *or* closed issues document this problem.
- [X] This is a bug, not a new idea.
- [X] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [X] This issue occurs on the latest vanilla TF2 update.

- [X] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [X] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues). [#2221](https://github.com/ValveSoftware/Source-1-Games/issues/2221)
- [ ] This issue occurs with DirectX level 100.
- [X] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [X] This issue occurs when using a listen server (using the `map` command ingame).
- [X] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. try to look for these maps to queue for casual
2. 
3.

#### Client Settings

- *Server or client:* 
- *Operating system:*  Windows 7
- *Team Comtress version:* 
- *Custom content:*  customized flawhud and autoexec
- *Launch options:*  -console -novid -nojoy -nosteamcontroller -nohltv -particles 1 -no_texture_stream
#### Driver Version

- *Graphics driver:* 
- *DirectX level:* 
#### Hardware Specs

- *CPU model:* 
- *GPU model:* 
- *RAM amount:* 
- *TF2 install location:* 
- *TC2 install location:* 
- *TC2 installation method:*

**Comment by melvyn2** [comment]
We can't change anything about casual, that's on valve's end.

**Comment by MikhailaTF** [comment]
> 
> 
> We can't change anything about casual, that's on valve's end.

That makes sense actually, my bad!
