### ISSUE TITLE
[IDEA] Discord Rich Presence

### ISSUE THREAD

**Issue by MeDerpWasTaken** [mastercomfig/team-comtress-2#479]
### Description

Somewhat simple, but add Discord Rich Presence support to TF2, things such as dynamic status, game invites, and other features included with Discord Rich Presence. 

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [x] This idea has been implemented in a mod. [Here](https://github.com/Kataiser/tf2-rich-presence) (there are probably other mods as well)
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Screenshots

![image](https://user-images.githubusercontent.com/62511835/97112059-41449180-16b0-11eb-8062-de78c4a48499.png)
![image](https://user-images.githubusercontent.com/62511835/97112098-72bd5d00-16b0-11eb-8c3a-722a533b23bf.png)

https://discord.com/developers/docs/rich-presence/how-to

**Comment by MeDerpWasTaken** [comment]
https://github.com/mastercomfig/team-comtress-2/issues/187#issuecomment-693492260

Ok so this may have been denied in that, but I'm not 100% sure, but also, I doubt discord will hack the game

**Comment by melvyn2** [comment]
I think that if this is open for consideration, then #187 needs to be reopened and this one closed.
> I doubt discord will hack the game

what?

**Comment by MeDerpWasTaken** [comment]
> > I doubt discord will hack the game
> 
> what?

> I don't think it's a good idea to integrate a competitor's technology within your own product.
that's what mastercoms said, which I assumed that they meant that discord would hack the game or something

**Comment by rcmaehl** [comment]
> that's what mastercoms said, which I assumed that they meant that discord would hack the game or something

Not sure how you got that but this request is very likely out of scope.

**Comment by agrastiOs** [comment]
Closing for the same reason as #187.
