### ISSUE TITLE
Enable unused headshot and backstab animations for MVM

### ISSUE THREAD

**Issue by Malfunktion-issues** [mastercomfig/team-comtress-2#484]
### Description

[As documented by Sigsegv](https://www.youtube.com/watch?v=UhvdkCp5of8)
I can see why Valve didn't enable them despite their completed state as the bomb path could quickly be cluttered with models, obscuring the team's view as well as likely effecting performance negatively. Thus, I'd propose the animations playing rarely (perhaps a 1-in-50 chance) or for them to only play on Giants if it's what deals them in. It would probably take a bit of work due to bots being coded to explode instead of ragdolling, but I think with as much care and detail put into them, they should see the light of day in action.

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [ ] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Screenshots

![pyro](https://user-images.githubusercontent.com/72053336/97126033-c4db9e00-1703-11eb-9a5a-f5eeb9b5e085.gif)
(I apologize for the jankiness, I tried like three different methods to record just the Pyro segment and the last best one didn't capture everything at full speed)
### Alternatives

1. 
2. 
3.

**Comment by DrCactusTF2** [comment]
These are already included in TC2

**Comment by condor00fr** [comment]
actually yes they are, exept airblast

**Comment by Malfunktion-issues** [comment]
Nice
