### ISSUE TITLE
Some cosmetics have different lighting which contrasts the player model

### ISSUE THREAD

**Issue by agrastiOs** [mastercomfig/team-comtress-2#489]
### Description

When a player passes under light or go into a dark area, his cosmetics might have different lighting than his player model. E.g.: player goes to a shadow, his body is dark while his hat is bright.

This is an issue with Source. Each item instance uses its own origin to decide what lightning it should react to, and most item makers did not look into the $illumpos. As decompiling every single cosmetic and changing its $illumpos, then recompiling would be incredibly time-consuming, it could be easily fixed by forcing all tf_wearables to use the shadow origin of its player owner ala CS:GO, which ficool2 has done: https://steamcommunity.com/sharedfiles/filedetails/?id=2152159089
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.

- [x] This issue occurs on the latest vanilla TF2 update.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources. (Technically both yes and no)
- [x] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).https://github.com/ValveSoftware/Source-1-Games/issues/2143
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Have a few cosmetics on the player
2. Go to a darker place in the map
3. Taunt or look at another player with cosmetics to see the lighting issues

### Screenshots
These are on Dustbowl, 1st Stage, right after BLU's spawn:
![8b866e40-f85e-11e6-9e12-a19607be41a4](https://cloud.githubusercontent.com/assets/15906773/23184550/e7d0059c-f888-11e6-9f29-ea688a247525.jpg)
 
![f024d9a6-f88e-11e6-81f1-fa0227f07054](https://cloud.githubusercontent.com/assets/15906773/23232183/0134fb3a-f953-11e6-9418-29c8ab8ded82.jpg)
 
This one is on Dustbowl, 2nd Stage:
![0c6a6a40-f88f-11e6-8290-40617ebafed5](https://cloud.githubusercontent.com/assets/15906773/23232216/16b8ee9e-f953-11e6-8ad4-d15d45075149.jpg)

#### Client Settings

- *Server or client:* Client 
- *Operating system:* Windows 10 20H2
- *Team Comtress version:* 0.0.8  
- *Custom content:* 
- *Launch options:* 
#### Driver Version

- *Graphics driver:* 
- *DirectX level:* 100 
#### Hardware Specs

- *CPU model:* 
- *GPU model:* 
- *RAM amount:* 
- *TF2 install location:* 
- *TC2 install location:* 
- *TC2 installation method:*

**Comment by MikhailaTF** [comment]
Was this not already addressed and fixed in [Release 0.0.9](https://github.com/mastercomfig/team-comtress-2/releases/tag/0.0.9)?

**Comment by agrastiOs** [comment]
Fixed in 0.0.9.
