### ISSUE TITLE
Allow higher and lower mat_picmip levels

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/team-comtress-2#51]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to set my textures to very low, but the game does not let me do it.

**Describe the solution you'd like**
Allow higher than 4 (or 2 on sv_cheats 1) and lower than -1

**Describe alternatives you've considered**
N/A

**Additional context**
Strip mipmaps from hud so it does not affect HUD.

**Comment by micwoj92** [comment]
@mastercoms mat_picmip 4 is allowed since https://github.com/mastercomfig/team-comtress-2/commit/cb0fc6acd51e4e97cc3187c1148aa0b9b5ffb157

Do you also plan to add support for higher quality textures?

**Comment by Damsen117** [comment]
No need for that, there's a mod already that hex edited and fixed the LoD values of every texture, bringing them to their highest quality possible. Same job should be done for this build, that's all.

**Comment by micwoj92** [comment]
> No need for that, there's a mod already that hex edited and fixed the LoD values of every texture, bringing them to their highest quality possible. Same job should be done for this build, that's all.

There is difference between mod workaround and feature that is built-in in the game.

**Comment by Yttrium-tYcLief** [comment]
What @Damsen117 is saying is that *this* project is focused on the engine/code itself, rather than game assets, and that such a fix would be better achieved by cleaning up the assets themselves, rather than hacky workarounds in code.

**Comment by micwoj92** [comment]
Ok, but can you change the picmip when in game or do you have to reload? I got his point, but I still think that mat_picmip -10 would be better than texture that needs restarting(dont know if thats true) to get worse quality.

**Comment by mastercoms** [comment]
Valve has been aware of this request for quite some time now and they have reasons to not allow for it. I did allow mat_picmip 4 because people have been using LOD bias anyways.
