### ISSUE TITLE
Disable being able to activate the B.A.S.E Jumper at the height of a simple jump

### ISSUE THREAD

**Issue by Ashetf2** [mastercomfig/team-comtress-2#512]
### Description

In OW, with Mercy and Echo you can't use their pasive (in few words, gliding) if the distance to the ground is less than the height of a simple jump. I think this would be good to implement in TF2 too, because how it is now, you may occasionaly activate the parachute when rocket jumping, ruining the power of the RJ.
### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives

1. 
2. 
3.

**Comment by treacherousfiend** [comment]
This might fall into a balance change, but its such a minor thing that I think this would count as QoL, unless anyone has any objections, i'll look into it.

**Comment by MeDerpWasTaken** [comment]
I mean just because something is minor doesn't make it so it's not a balance change

**Comment by wgetJane** [comment]
this seems like an unncessary change

i see people often activate the parachute at jumping height to move a bit faster or glide over a gap, so this change would affect such uses of the base jumper

i also don't really see how being able to activate the parachute at jumping height affects rocket jumping negatively

**Comment by Shrinks99** [comment]
Frequent B.A.S.E Jumper user here, I quite like this feature of the weapon and would be personally bummed if it got removed.  Right now the parachute can be activated whenever a user is in the air, changing this to be height related is a (relatively) major adjustment to how players think of the weapon functioning as now they need to take into account their distance from ground.  This also has the potential to impact its current use for negating fall damage by opening the parachute just before hitting the ground.

This should definitely be considered a balance change and not an objective QoL fix.

**Comment by treacherousfiend** [comment]
If I do work on this (likely won't, judging by the comments), I think it'd be simply that for a couple frames (no more than like 1/4 second) after you press jump you can't parachute, simple to stop people from cancelling their momentum by accidentally double tapping space.

I agree that disabling parachuting based on height is a bad idea, both for jumping and falling.

**Comment by Ashetf2** [comment]
As treacher said, thats what im trying to say (im not a english native speaker)

**Comment by Shrinks99** [comment]
@Ashetf2 No worries, your English is fine!  The instant deploy time is a characteristic of the weapon and changing its time to deploy will affect using it to cancel jumps which you've brought up as a bug but could also be viewed as a feature.  I just disagree that this is an objective bug / QoL fix, it's a balance change that affects how the weapon is used.

**Comment by Ashetf2** [comment]
Closing after 2 years. I don't know what i was thinking before

**Comment by micwoj92** [comment]
This is good idea, please reopen. base jumper just needs multiple styles.
![image](https://user-images.githubusercontent.com/45581170/184558814-600c3b84-0717-4eaa-87db-3a92aca11ef6.png)
