### ISSUE TITLE
Mount via gameinfo.txt to prevent copying 28 gb game

### ISSUE THREAD

**Issue by Xephobia** [mastercomfig/team-comtress-2#53]
**Is your feature request related to a problem? Please describe.**
Mounting would be great because copying an entire 28GB game is not nice

**Describe the solution you'd like**
Posibility to mount tf2 games files for team comtress 2

**Describe alternatives you've considered**
i have copied the gameinfo.txt from the tffolder of my tf2 install and copyed it on the tf folder of team comtress 2, i modyfied it so anything pointing to a tf2 vpk file would point to a vpk file of my tf2 install, hoewer it did nothing when trying to launch with start_tf2.bat or hl2.exe

**Comment by Yttrium-tYcLief** [comment]
While convenient in some cases, it might obfuscate the project a bit too much, and cause unintentional bugs.

**Comment by Yttrium-tYcLief** [comment]
We might revisit this in the future, but for now we're going to stick with duplicate game files, for ease of development and debugging.

**Comment by Margen67** [comment]
You can probably make symbolic links to the .vpks (the biggest files) instead of copying them, but it might be too much trouble to be worth it.

**Comment by uis246** [comment]
There are also hard links when files in same fs
