### ISSUE TITLE
Disabling the waiting for players period

### ISSUE THREAD

**Issue by RealHoriuchi** [mastercomfig/team-comtress-2#533]
### Description
mp_waitingforplayers_disable
A new boolean convar which disables the waiting for players period when the server loads a map

### Checklist
- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

**Comment by melvyn2** [comment]
`mp_waitingforplayers_cancel`

**Comment by Margen67** [comment]
> 
> 
> `mp_waitingforplayers_cancel`

`mp_waitingforplayers_time 0`
