### ISSUE TITLE
TF2 unused voice lines

### ISSUE THREAD

**Issue by Melonenyoshi** [mastercomfig/team-comtress-2#539]
### Description

  So there are many unused Voice Responses in tf2 like the achievment voicelines, and the casual win Voice Responses(those are sometimes used) i think,  rank up(these are used in competitive but it would also be cool if they were in casual) Voice Responses and i think everybody would appreciate it if those were used that would bring a little fresh air to the voice lines 
### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [x] This feature has existed in the vanilla game but was removed.        Or  never used
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives

1. 
2. 
3.

**Comment by micwoj92** [comment]
out of scope.

**Comment by Melonenyoshi** [comment]
ok

**Comment by Juesto** [comment]
This is more suited for the assets repository, but it's still out of scope because it implies making new sounds instead of fixing assets.

**Comment by Melonenyoshi** [comment]
Wait why making new sound aren't those already in the game

**Comment by treacherousfiend** [comment]
This would be the right repo, since the sounds already exist... but we are no longer (for the time being) doing game fixes, instead we are focusing on engine fixes, which is basically anything that isn't specifically TF2 related.

**Comment by Juesto** [comment]
> Wait why making new sound aren't those already in the game

Sorry for my misassumption, but yeah, it goes to the assets repository if its soundscripts.
