### ISSUE TITLE
Add new "Ready" responses for remain class in MVM

### ISSUE THREAD

**Issue by Ashetf2** [mastercomfig/team-comtress-2#543]
### Description

Well, as you can see, Scout, Pyro, Demoman, Sniper and Spy doesnt have a "Ready" specific response (they use the "Go go go!" response), but there's already some "Ready" responses for that classes, added in the MYM update i think, for the matchmaking. Some of these responses can be reused for MVM.
(Pyro only has one specific response).

_Also, can you fix that if someone gets ready when someone is using his response, it cuts the response (with the other response)_
### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives

1. 
2. 
3.

**Comment by micwoj92** [comment]
Out of scope.

**Comment by Ashetf2** [comment]
ok
