### ISSUE TITLE
Spy can block bullets when disguised

### ISSUE THREAD

**Issue by joshuadinada** [mastercomfig/team-comtress-2#547]
### Description

When a spy disguises, a set of invisible weapons are created, at his feet, that don't follow him and stay where the spy started disguising, BUT they can block bullets.
Better documentation here https://www.youtube.com/watch?v=bDlgOUOJqWk

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs on the latest vanilla TF2 update.

### Reproduction

1. Disuise (preferably as the pyro or as a soldier, because their weapons are rather big)
2. Get someone to shoot at your feet

**Comment by Ashetf2** [comment]
Fixed by Valve in the June 21 Patch: https://www.teamfortress.com/post.php?id=139819
