### ISSUE TITLE
Cvar to clear backbuffer each frame

### ISSUE THREAD

**Issue by henke37** [mastercomfig/team-comtress-2#558]
### Description
A cvar that when enabled clears the backbuffer with a solid color each frame.

This would make it more bearable when a mapper allows the camera to point at an area with no faces occluding the void and the 2D skybox isn't in PVS. This leads to remains of old frames "smearing" as the camera is moved around.

This effect is more commonly incorrectly known as a "leak" and "hall of mirrors".

To get the best of both worlds, make the cvar have three modes, always clear, never clear and clear only when no pvs sky (default).

### Checklist

- [X] None of the open *or* closed issues document this idea.
- [X] This is a new idea, not a bug.
- [X] This idea does not seriously affect game balance.
- [X] This is obviously an improvement, not something that people commonly disagree on.
- [X] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [X] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives

1. 
2. 
3.

**Comment by Margen67** [comment]
`gl_clear 1`?

**Comment by melvyn2** [comment]
> `gl_clear 1`?

`gl_` cvars are made for OpenGL, `r_` cvars relate to general rendering. `r_backbuffer_clear` seems reasonable.

**Comment by treacherousfiend** [comment]
just checked, gl_clear works on DX as well, even comes with a version that makes the backbuffer flash random colors just to give you eye strain (or to find small leaks)
