### ISSUE TITLE
Sandman slowing mechanic can be bypassed by rapidly pressing A and D.

### ISSUE THREAD

**Issue by IFoppyI** [mastercomfig/team-comtress-2#581]
When an enemy is hit with the sandman ball, the enemy is given a speed debuff depending on how far the ball has travelled to its target. This speed debuff can be bypassed by simply rapidly pressing A and D while moving forward.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs on the latest vanilla TF2 update.

- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Have an enemy scout equip the sandman and use the secondary "ball" attack onto you, max distance.
2. Rapidly press A and D and you will move faster than simply holding W

#### Client Settings

- *Server or client:* Both
- *Operating system:* Any
- *Team Comtress version:* Unsure
- *Custom content:* None
- *Launch options:* None

**Comment by Sirbucket** [comment]
This also applies to the bonk speed penalty and the Natascha

**Comment by LordExor** [comment]
This was already fixed.
