### ISSUE TITLE
Ammo Vision for Engineer Class

### ISSUE THREAD

**Issue by IFoppyI** [mastercomfig/team-comtress-2#582]
The engineer is class that requires knowledge of ammo packs and good spots to set up your sentry, but what if the engineer could see ammo packs through walls and only at a certain distance?

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [x] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Screenshots
![image](https://user-images.githubusercontent.com/84149603/118170437-14f82480-b3f8-11eb-9158-146cf1754f47.png)

### Alternatives

1. Engineer is able to see sources of Ammo/Metal through walls when nearby them.
2. This is a small distance to not encourage engineers to over extend.
3. This will help new engineers to find sources of Ammo in active play instead of having to depend on only their dispenser or the resupply cabinet.

**Comment by treacherousfiend** [comment]
This is a balance change, TC2 is only for bug fixes and optimizations

**Comment by Sky-rym** [comment]
No thanks, that's what map knowledge is for.
Although an interesting idea for a custom weapon, it doesn't work as a balance change for Engineer as a whole.
