### ISSUE TITLE
[QoL] Add Curly Bill’s Model Fixes Overhaul

### ISSUE THREAD

**Issue by DankMachine** [mastercomfig/team-comtress-2#584]
### Description
I would like to suggest a Quality of Life addition that adds touch-ups to most classes.
Some fixes are related to clipping issues like Soldier’s jacket and Pyro’s hand.
Some are for coloring issues like Spy bot’s tie and Scout bot’s head.
Engie bot’s head lighting is fixed.
Demoman’s jacket is cleaned to not clash with other cosmetics.
BLU Scout’s pants are now blue.

### Checklist
- [X] None of the open *or* closed issues document this idea.
- [X] This is a new idea, not a bug.
- [X] This idea does not seriously affect game balance.
- [X] This is obviously an improvement, not something that people commonly disagree on.
- [X] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [X] This idea has been implemented in a mod. https://gamebanana.com/mods/198715
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Screenshots
![6EDA1C9A-E3C1-4FA2-BF02-B732B7E5C97F](https://user-images.githubusercontent.com/65761073/118342136-bf02aa00-b4e7-11eb-8e76-6cbd157c1e23.jpeg)
![32A30FFE-A1D6-4A70-9C43-5E57615EB617](https://user-images.githubusercontent.com/65761073/118342138-c033d700-b4e7-11eb-8782-6f3a8fa45f56.jpeg)
![F8A562F4-E4F9-4ED5-A208-2AC0FD8BC734](https://user-images.githubusercontent.com/65761073/118342139-c033d700-b4e7-11eb-959d-a027fab11e6f.jpeg)
![BC3694FB-4827-4EA5-AF53-A8F2669941AA](https://user-images.githubusercontent.com/65761073/118342142-c0cc6d80-b4e7-11eb-98e3-a708bc1704bb.jpeg)
![21B322DD-12A7-46D8-9D50-1B8820263B60](https://user-images.githubusercontent.com/65761073/118342143-c1650400-b4e7-11eb-85c6-9c8ef6941783.jpeg)
![43CB2151-CA29-41EB-B699-9544A6B1C074](https://user-images.githubusercontent.com/65761073/118342146-c1650400-b4e7-11eb-9f14-912ea23c92ea.jpeg)
![8F915F1B-5C81-4E02-BDEC-03571BF98805](https://user-images.githubusercontent.com/65761073/118342148-c1fd9a80-b4e7-11eb-97d7-12d00e692187.jpeg)

**Comment by DankMachine** [comment]
The purpose of Demoman’s vest change is because it stands out when using cosmetics that remove his grenades (ex. Dead of Night)

**Comment by treacherousfiend** [comment]
this would be more fitting for the [assets repo](https://github.com/mastercomfig/team-comtress-2-assets), and i believe most of these have been fixed anyway.

**Comment by DankMachine** [comment]
Oh good, these have been addressed. Thanks for letting me know!
