### ISSUE TITLE
Baby-face's blaster hitboxes

### ISSUE THREAD

**Issue by Kidcoder64** [mastercomfig/team-comtress-2#592]
### Description
I don't know if this as been requested before, but could you fix the hitboxes lagging behind the player on the baby-face? that kinda seems like the obvious bug to fix. Again, sorry if it's already been fixed.

**Comment by melvyn2** [comment]
according the @wgetJane this was never a real issue even in real tf2.

**Comment by Kidcoder64** [comment]
> according the @wgetJane this was never a real issue even in real tf2.

yeah, but it should still be fixed

**Comment by treacherousfiend** [comment]
there's nothing to fix. the issue doesn't exist

**Comment by melvyn2** [comment]
...you can't fix something that doesn't exist.

**Comment by Kidcoder64** [comment]
Wasn't it the reason why the baby face's was given the "lose boost on hit" penalty?

**Comment by treacherousfiend** [comment]
No, the issue never existed, and it was likely given that to help balance it because it was overpowered.

**Comment by Kidcoder64** [comment]
oh, sorry then.

**Comment by mastercoms** [comment]
If lagging hitboxes existed, it wouldn't be just for the BFB, but also rocket jumping players. Obviously not true.
