### ISSUE TITLE
Clean the tf2 texture/code files

### ISSUE THREAD

**Issue by TwiceDaIce** [mastercomfig/team-comtress-2#596]
### Description

Remove excess files from the tf2 texture vpk files, reducing game size and clutter.
### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Screenshots

https://tcrf.net/Team_Fortress_2/Unused_Textures
### Alternatives

1.  mark extra files and textures as useless, as to reduce clutter

**Comment by agrastiOs** [comment]
To be clear, are you suggesting that unused textures, materials, sounds and scripts are removed?

What are the "code files" you are mentioning in the title?

**Comment by pvorisek25** [comment]
What if some custom servers use these assets?
