### ISSUE TITLE
Disabled r_hunkalloclightmaps

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [mastercomfig/team-comtress-2#60]
**Is your feature request related to a problem? Please describe.**
A thing that is always clear is that r_hunkalloclightmaps is a legacy feature from the old days of
quake/goldsrc where you cannot used over  4k lightmaps (idk how people manages to get those values)
triggering the well know **Engine Hunk Overflow**

**Describe the solution you'd like**
Turning off/nuking makes that error being gone.

**Describe alternatives you've considered**
none.

**Additional context**
https://developer.valvesoftware.com/wiki/Engine_Hunk_Overflow
![image](https://user-images.githubusercontent.com/12750944/91741600-92d21380-eb7a-11ea-8a32-377e190ec714.png)

**Comment by mastercoms** [comment]
Hunk memory is already increased.
