### ISSUE TITLE
Support for more than 4 loadout slots (via console commands, saves it locally with a .cfg)

### ISSUE THREAD

**Issue by gabrielwoj** [mastercomfig/team-comtress-2#605]
### Description

Add a console command that let people export (dump) their loadouts to a .cfg (locally), with no limit (or over 4 slots). The game must check if the item is on the player's backpack before successfully equipping the items.

The .cfg is human-readable and edit-able, so players can add more than 4 loadouts and switch in the game with no hassle.

The items in the .cfg uses the serial ID from items (example: https://steamcommunity.com/id/Zeugziumy/inventory/#440_2_8766904376 , the ID is the last set of numbers).

The serial ID is to avoid the .cfg load the same item by accident (let's say someone has 2 of the same item, but each of them have different styles appied, this is why the ID would be important).

A problem with that: It would be possible to wear conflicting items, however, the game already automatically unequips them as soon as possible, so I don't think that would be much of an issue.

Expand the load_itempreset command to support the extra slots (or add another console command to not conflict with loadouts saved on Steam's servers, like "load_local_itempreset"). Having no limit to the loadout slots would be ideal (or at least until the limit that .cfg files can handle).

EDIT: The command could export the active loadouts, and each time the command is run again, a new batch of items (a new slot) is saved on the same .cfg. It skips if it the same set of items was already saved before.

I don't think it's possible to add more loadout slots via the loadout screen, I'm pretty sure the loadouts are saved on Steam servers.

TF2 has way, way, WAY too many customization options, and way too little loadout slots. We have festivizers, paints, qualities, decals, taunts, custom names/descs and so on. In my case, all of my classes have more than 4 loadouts, and it's a hassle to keep equipping each item individually everytime I want to use a set in specific.

In terms of weapons, Soldier and Pyro has a lot of weapons, but again, we only have 4 slots.

Aditionally, this game has a bunch of different game modes, as well game modes made by the community (Vs. Saxton Hale, for instance). Along with the gamemodes, different weapons can be used depending on the side (Attack or Defense), expanding the loadout table would make things easier to manage, depending on the gamemode and side.

4 slots was enough back when the system was introduced, but it has been several years since its inclusion, and way too many items and customization tools has been added since then.

Thanks.

### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [x] (?) This feature has existed in the vanilla game but was removed (I think there was once a way to equip items via console commands, but not actually loadout slots).
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives

None I can think of.

**Comment by micwoj92** [comment]
Nice potato medal
