### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by karriszou** [mastercomfig/team-comtress-2#621]
### Description
- *Operating system:* Windows 10
- *IDE:* Visual Studio 2022

I cloned the lastest code(commit: 568844aeacf40e80a63cdf8f083bbeeaf0dded94) and build it in vs2022 but blow error occured:
**team-comtress-2\src\public\tier0\memoverride.cpp(276,8): error C2382: '_msize_base': redefinition; different exception specifications**
https://github.com/mastercomfig/team-comtress-2/blob/568844aeacf40e80a63cdf8f083bbeeaf0dded94/src/public/tier0/memoverride.cpp#L276
It seem that the function override declaration is conflict with it:
https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.16299.0/ucrt/corecrt_malloc.h#L103

How do i compile it?

**Comment by micwoj92** [comment]
> Try removing the `noexcept` keyword. The conflict is caused due to the different exception specifications (one is with noexcept, and one is without), as noted in the error message.

prs welcome

**Comment by mastercoms** [comment]
PRs aren't welcome since this is a change for the latest Windows SDK
