### ISSUE TITLE
Not starting on Linux

### ISSUE THREAD

**Issue by kittyron** [mastercomfig/team-comtress-2#642]
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.

- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Launch hl2.sh
2. Get an error:
`./hl2.sh: line 69: /var/home/user/Games/tf2/hl2_linux: cannot execute: required file not found`
Exact line that error references
`${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"`
#### Client Settings

- *Server or client: Client* 
- *Operating system: Fedora Silverblue Kernel: 6.1.14-200* 
- *Team Comtress version: 1.1.1* 
- *Custom content: none* 
- *Launch options: none* 
#### Driver Version

- *Graphics driver:* 
- *DirectX level:* 
#### Hardware Specs

- *CPU model:* 
- *GPU model:* 
- *RAM amount:* 
- *TF2 install location:* 
- *TC2 install location:* 
- *TC2 installation method:*

**Comment by kittyron** [comment]
I have hl2_linux in the same folder as hl2.sh. Also tried running it as sudo and got the same error.

[user@fedora tf2]$ ls
bin         hl2.sh        srcds.bat          start_tf2.sh
hl2         LICENSE_SDK   start_server.bat   steam_appid.txt
hl2.bat     platform      start_server.sh    tf
hl2_linux   README.md     start_tf2.bat      thirdpartylegalnotices.txt

**Comment by mastercoms** [comment]
you haven't copied over a tf2 installation, you need to set up a separate tc2 folder with the files from tf2 live and then install this on top of that. there's a community script which manages this.

**Comment by mastercoms** [comment]
https://github.com/mastercomfig/tf2-patches/blob/60e1a370414f5c2a0a541175ad7bf81ba4fdb977/game_clean/link.sh

**Comment by mastercoms** [comment]
With this script, make a tc2 folder. then in that folder, make a folder called scripts and put this in there. make another folder called game as well. then run link.sh, it will link your steam tf2 to the tc2 folder

**Comment by kittyron** [comment]
I ran the script and got this error:

cp: cannot stat 'copy/': No such file or directory
ln: failed to create symbolic link '../game/hl2': File exists
ln: failed to create symbolic link '../game/platform': File exists
ln: failed to create symbolic link '../game/tf/maps': No such file or directory
mkdir: cannot create directory ‘../game/tf/materials’: No such file or directory
ln: failed to create symbolic link '../game/tf/materials/models': No such file or directory
ln: failed to create symbolic link '../game/tf/materials/vgui': No such file or directory
ln: failed to create symbolic link '../game/tf/media': No such file or directory
ln: failed to create symbolic link '../game/tf/resource': No such file or directory
ln: failed to create symbolic link '../game/tf/scripts': No such file or directory
ln: target '../game/bin/': No such file or directory
ln: target '../game/tf/': No such file or directory
ln: target '../game/tf/': No such file or directory

It copied over only hl2, hl2.sh and platform to game folder.

**Comment by ReplayCoding** [comment]
How are you compiling TC2? Are you using #629?

**Comment by kittyron** [comment]
Script now works. I thought that all I had to do was to copy the script that mastercoms linked and not download the whole GitHub repo. But the error remains: `./hl2.sh: line 69: /var/home/user/Downloads/tf2-patches-base/game/hl2_linux: cannot execute: required file not found`

**Comment by kittyron** [comment]
> How are you compiling TC2? Are you using #629?

I'm not compiling TC2 myself, I'm using version from releases

**Comment by getchoo** [comment]
are you using the flatpak version of steam?

**Comment by kittyron** [comment]
> are you using the flatpak version of steam?

Yes I am

**Comment by getchoo** [comment]
it doesn't work for tc2. i tried messing with it but couldn't figure it out - it must be something going on with their modified runtime. you can layer the steam package from the rpmfusion repository with `rpm-ostree` and it'll work fine

**Comment by kittyron** [comment]
> it doesn't work for tc2. i tried messing with it but couldn't figure it out - it must be something going on with their modified runtime. you can layer the steam package from the rpmfusion repository with `rpm-ostree` and it'll work fine

Installed steam with rpm-ostree and hl2.sh now launches, but I get another error:

SDL video target is 'x11'
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
OpenGL: AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.49, 6.1.14-200.fc37.x86_64) 4.6 (Compatibility Profile) Mesa 22.3.6 (4.6.0)
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_ARB_buffer_storage: NOT AVAILABLE
GL_EXT_texture_sRGB_decode: AVAILABLE
AppFramework : Unable to load module engine.so!
Unable to load interface VCvarQuery001 from engine.so

**Comment by kittyron** [comment]
If it can help, ldd bin/engine.so returns:
	linux-gate.so.1 (0xf7faa000)
	libtier0.so => not found
	libvstdlib.so => not found
	libsteam_api.so => not found
	libSDL2-2.0.so.0 => not found
	libopenal.so.1 => not found
	libcurl-gnutls.so.4 => not found
	libm.so.6 => /lib/libm.so.6 (0xf7ec3000)
	libdl.so.2 => /lib/libdl.so.2 (0xf7ebe000)
	libstdc++.so.6 => /lib/libstdc++.so.6 (0xf6e00000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xf7eb7000)
	/lib/ld-linux.so.2 (0xf7fac000)
	libc.so.6 => /lib/libc.so.6 (0xf6c14000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xf7e92000)

**Comment by getchoo** [comment]
when you ran `link.sh` did you put the path to your tf2 installation as an argument? it defaults to the regular package installation, so if you didn't it could explain not finding engine.so and the `No such file or directory` warnings from your previous responses

**Comment by kittyron** [comment]
> when you ran `link.sh` did you put the path to your tf2 installation as an argument? it defaults to the regular package installation, so if you didn't it could explain not finding engine.so and the `No such file or directory` warnings from your previous responses

When I had TF2 installed through flatpak steam then yes I put TF2 installation as an argument, but now I installed TF2 through normal steam. Tried specifying path to TF2 installed through normal steam and the same error shows up.

**Comment by kittyron** [comment]
I can see that I have engine.so in game folder.

**Comment by kittyron** [comment]
Don't know what I did, but it started working (didn't change anything from the last time I tried to run).  Except the game is too bright, and I get error about limited glyph support, but maybe I will open another issue if someone else didn't.
![Screenshot from 2023-03-07 22-42-17](https://user-images.githubusercontent.com/127242677/223561313-62875280-26db-45e1-bf09-6066b9821cf1.png)
![Screenshot from 2023-03-07 22-44-43](https://user-images.githubusercontent.com/127242677/223561413-839a7bda-0aad-49a8-8ac4-ab2d1e29c65c.png)
![Screenshot from 2023-03-07 22-46-09](https://user-images.githubusercontent.com/127242677/223561425-307e8ed9-7f16-4583-97d2-9ee81ea653e4.png)

**Comment by kittyron** [comment]
Right now I doubt I installed it without screwing something up, there are too many bugs.

- Soldier going to sleep at the end of the taunt
- Disappearing weapons after shooting
- Game is too bright

https://user-images.githubusercontent.com/127242677/223563118-724d4a0e-1ef0-482b-893a-a39e04c7c92f.mp4


https://user-images.githubusercontent.com/127242677/223563137-e2e1ca0c-4874-4099-99d0-f8b3d8d4f8e2.mp4
