### ISSUE TITLE
Sniper scope overlay can be removed with a HUD

### ISSUE THREAD

**Issue by RicochetYT** [mastercomfig/team-comtress-2#647]
### Description
As the title says, using some modifications to a custom HUD, you can make the sniper scope disappear, giving you an advantage. To my knowledge, this still occurs on TC2, but I haven't been able to test it due to the lack of HUDs on the old version and laziness.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs on the latest vanilla TF2 update.

- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [ ] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Add the following to "hudanimations.txt"
```
// Break Sniper scope border.
event ScopeRemoval
{
	Animate HudScope Position	"9999 9999" Linear 0.0 0.0
}

event DamagedPlayer
{
	RunEvent ScopeRemoval 0.0
}
```
2. Add the following to autoexec.cfg or execute it manually:
```
alias remove_scope "sv_cheats 1; testhudanim scoperemoval"
remove_scope
```
3. Damage a player on any server, the sniper scope will be invisible for the rest of the time TF2 is running.

### Screenshots

![image](https://user-images.githubusercontent.com/36606403/224580198-b19b176d-b98b-4c59-9fd2-90fdc2a40049.png)

#### Client Settings

- *Server or client:* Client 
- *Operating system:* Any 
- *Team Comtress version:* Any 
- *Custom content:* HUD, nothing else really matters 
- *Launch options:* N/A

**Comment by mastercoms** [comment]
Duplicate
