### ISSUE TITLE
441 app

### ISSUE THREAD

**Issue by UnionOfUniverses** [mastercomfig/team-comtress-2#7]
Program didn't download 441 app, only 440 and 232251.

**Comment by mastercoms** [comment]
Is this fixed with 0.0.6?

**Comment by Knucklestf** [comment]
![image](https://user-images.githubusercontent.com/7910600/90585631-4f9f9a00-e1a3-11ea-9ecd-47fe7aa9b0d0.png)
Looks to be for me
