### ISSUE TITLE
Casual Mode is missing the Meet Your Match voicelines.

### ISSUE THREAD

**Issue by qballking4** [mastercomfig/team-comtress-2#76]
**Is your feature request related to a problem? Please describe.**
Special lines for all classes were created in the Meet Your Match update for Casual and Competitive. The Blue Moon update in 2018 seems to have broken the voicelines in Casual Mode. After that update, the classes no longer say those lines and only battle cry lines play. For example, here is a video demonstrating them before they stopped working.

https://youtu.be/HpRHt5psw-s

5:00: You can hear all of the classes bragging on how they won.

9:56: You can hear soldier say "I will not stand for losing!"

17:35: Round starts and you hear scout saying lets get a win, and soldier saying dibs on the medic.

I'm pretty sure there's more but I don't want to have you watch all of it. I'm sure you get my idea now.

I have a file that I have edited to make them work again. Here is how it previously looked, and never changed. (This is from tf/scripts/talker inside tf2_misc_dir.vpk)

Rule PlayerFirstRoundStartCompEngineer
{
    criteria ConceptPlayerRoundStartComp IsEngineer IsFirstRound IsNotComp6v6 40PercentChance
    Response PlayerFirstRoundStartCompEngineer
}

All I did was remove Comp from all of that, and they worked again for all classes. It seems that "IsNotComp6v6" doesn't do its job anymore so maybe that's the culprit.

**Describe the solution you'd like**
Fix them in Casual Mode. Only battle-cries play now which seems to be unintended as I can't find the change in the patch notes anywhere.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by Yttrium-tYcLief** [comment]
Unfortunately, while this is an issue in the live version of TF2, it actually *doesn't* seem to be a bug present in TC2, since the codebase is from mid 2017. Additionally, it would be impossible for us to test this with TC2, since starting a competitive match requires the matchmaker and Valve servers.
