### ISSUE TITLE
Replace the viewmodels with more consistent ones.

### ISSUE THREAD

**Issue by Damsen117** [mastercomfig/team-comtress-2#78]
As title says, replace the viewmodels that are inconsistent to the playermodel of the class, like Sniper, he doesn't wear two gloves, he wears only one, and only in his left with a watch. Closest example of this is Team Fortress 2 Classic, but the coloring isn't as consistent as it is in that sourcemod, like Scout's viewmodel, his skin isn't as dark there, so it's not color-accurate.

**Comment by FIying-Scotsman** [comment]
This project is to _fix the bugs in the code_ and to bring it up to spec but your suggestion is a model fix which is out of scope.

If you want to play with fixed view models I'd recommend TF2 Classic in that case.

**Comment by Yttrium-tYcLief** [comment]
This is a game asset issue and falls outside the scope of this project. Hopefully it gets addressed in the future though!
