### ISSUE TITLE
[bug fix request]pomson 6000 lacks third person reload animation

### ISSUE THREAD

**Issue by vlad55523** [mastercomfig/team-comtress-2#83]
widely known bug, there is no reload animation for the pomson 6000

**Comment by Yttrium-tYcLief** [comment]
I've tested this a bit and it seems like in retail TF2, the pomson does reload in third person, although it uses the default shotgun animation so it looks a bit wonky. In TC2, it just plays the idle stand animation, with absolutely no reload animation.

Considering this is likely a bug with the leaked build that TC2 is based on, as opposed to a bug that TC2 introduced, and considering this bug does not seem to exist in retail TF2 (although the real game needs better art), I don't think this is an appropriate issue.
