### ISSUE TITLE
[bug fix request]gas passer explode on ignite upgrade in mvm has no type of damage

### ISSUE THREAD

**Issue by vlad55523** [mastercomfig/team-comtress-2#85]
it simply is a typeless damage source such as melee weapons and medic shield when imo it should deal fire damage

**Comment by Yttrium-tYcLief** [comment]
TC2 is not the place for balance discussions or suggestions. This project is purely focused on QoL, bugfixing, and optimization.

**Comment by mastercoms** [comment]
I think this would fit as a viable bug fix for Comtress, but given that this is a build of the game before Jungle Inferno, we can't really fix Valve's own implementation in any useful way, unfortunately.
