### ISSUE TITLE
[Request] civilian class for VIP gamemode

### ISSUE THREAD

**Issue by ObsoleteGuy** [mastercomfig/team-comtress-2#88]
It would be a lot of fun if they keeped the civilian class for vip gamemode and as far i know the class still on the game but unused

**Comment by FIying-Scotsman** [comment]
The class is still there (kind of) but there isn't any model for it and there isn't any logic for the VIP game mode.

Why not just play TF2 Classic as it has the Civilian mode (including model) pretty much complete?

**Comment by ObsoleteGuy** [comment]
TF2 Classic is cool but theres a lot of toxic kids and mic spammers, i think adding the civilian on normal tf2 would be interesting

**Comment by FIying-Scotsman** [comment]
You'd have to rewrite how TF2 handles classes (like the TF2 Classic team had to) and write a whole new gamemode on top which is a huge effort in itself and in my opinion not really worth it when TF2C has done it already. 

We'd be effectively re-treading the same ground for little pay off as the gameplay would end up the same as TF2C.

**Comment by HurricanePootis** [comment]
Bruh this isn't tf2c.

**Comment by ObsoleteGuy** [comment]
why you guys are so bothered by this request? jeez is just a request.

**Comment by treacherousfiend** [comment]
You did kind of miss the point of comtress, it's not meant as a "bring literally everything possible into tf2" build, its meant for QoL, performance, and bug-fixing. this issue is none of those.

**Comment by Yttrium-tYcLief** [comment]
For clarification: TC2 is not meant to be a new version of TF2 that everyone goes and plays. TC2 is meant to be a huge swathe of bugfixes, optimizations, and QoL additions that eventually (hopefully) get merged into the base game.
