### ISSUE TITLE
Reenable func_camera

### ISSUE THREAD

**Issue by henke37** [mastercomfig/team-comtress-2#97]
**Is your feature request related to a problem? Please describe.**
It's a nice gimmick entity that is disabled in tf2 for resource use reasons.

**Describe the solution you'd like**
The number of rendertextures in the mod needs to be increased so that the entity can work correctly.

**Describe alternatives you've considered**
There are no workarounds for this.

**Comment by Yttrium-tYcLief** [comment]
Resource consumption needs to be studied, and it remains to be seen if this could really just be "enabled", or if re-implementation would be necessary, but this could certainly be explored.

**Comment by micwoj92** [comment]
Did you have time to study it yet @Yttrium-tYcLief ?

**Comment by Yttrium-tYcLief** [comment]
No, I'm not really much of a programmer. I just meant that as a form of intake assessment.
