### ISSUE TITLE
Server queue system

### ISSUE THREAD

**Issue by henke37** [mastercomfig/team-comtress-2#98]
**Is your feature request related to a problem? Please describe.**
Its an incredible pain to try and join a full server. Its a free for all when a slot is opened.

**Describe the solution you'd like**
The server retains a queue of clients waiting to join and reserves open slots for specific clients until they've connected.

**Describe alternatives you've considered**
There is no real solution to the issue, but private servers can set a password to keep people from connecting.

**Additional context**
Gonna need several timeouts to prevent slow/disappearing clients from hogging a slot forever.

**Comment by Yttrium-tYcLief** [comment]
This would be a significant amount of new development work and would require substantial access to the TF2 matchmaker, which we do not have.

**Comment by maximsmol** [comment]
Actually this is unrelated to the GC afaik. So I think this is a good idea. Question tho: does the auto-connect option on the "server is full" dialog not work? I am not sure whether it picks people in first in firs out order or just whoever manages to get in first. If it's the former then this is already implemented, otherwise we can implement it

**Comment by micwoj92** [comment]
tagging https://github.com/ValveSoftware/Source-1-Games/issues/1644

**Comment by henke37** [comment]
My understanding is that the autoconnect option runs entirely on the client. Whomever happens to autoupdate at the right time wins. It's a free for all.

**Comment by uis246** [comment]
Join queue. Good, we need it

**Comment by mastercoms** [comment]
I think this is more of a Steam issue since the server itself cannot handle this in a reasonable way.

**Comment by uis246** [comment]
Why steam? It is about in-game server browser
